apps/web/app/(authenticated)/(app)/[tenantSlug]/TeamSwitcher.tsx

Using the native sign out button.

Chore: remove useAuth and use the Clerk sign out button

---

apps/web/app/(auth)/auth/sign-in/[[...sign-in]]/page.tsx
apps/web/app/(auth)/auth/sign-in/layout.tsx
apps/web/app/(auth)/auth/sign-up/[[...sign-up]]/page.tsx
apps/web/app/(auth)/auth/sign-up/layout.tsx
apps/web/app/(auth)/layout.tsx

Check if a user is signed in and redirect them back to /app

Check clerk status

---

apps/web/app/(authenticated)/auth/sso-callback/[[...sso-callback]]/page.tsx

Spinner was at the top and made me sad.

center the spinner for ssocallback

---

apps/web/app/(authenticated)/(app)/app/apis/DeleteAPI.tsx
apps/web/app/(authenticated)/(app)/app/apis/row.tsx
apps/web/lib/trpc/routers/api.ts

this also deletes the keys associated with it. 
- Update tRPC to handle this 
- Adds delete to row 
- Delete dialog

Add the ability to delete api,

---

apps/web/app/(authenticated)/(app)/app/[apiId]/CreateKey.tsx
apps/web/app/(authenticated)/(app)/app/keys/[keyId]/client.tsx
apps/web/app/(authenticated)/(app)/onboarding/page.tsx
apps/web/app/(authenticated)/auth/sign-in/[[...sign-in]]/page.tsx
apps/web/app/(authenticated)/auth/sign-in/layout.tsx
apps/web/app/(authenticated)/auth/sign-up/[[...sign-up]]/page.tsx
apps/web/app/(authenticated)/auth/sign-up/email-code.tsx
apps/web/app/(authenticated)/auth/sign-up/layout.tsx
apps/web/components/ApiKeyTable/table.tsx

Fixes:
- Signup
- Refreshing pages
- Fixes Bytes as number
- Fix deletion refreshes

Bug fixing

---

apps/web/app/(authenticated)/(app)/app/[apiId]/keys/new/CreateKey.tsx
apps/web/app/(authenticated)/(app)/app/apis/CreateAPI.tsx
apps/web/app/(authenticated)/(app)/app/keys/CreateKey.tsx
apps/web/app/(authenticated)/(app)/onboarding/client.tsx

Adds button states for disabling

---

apps/web/app/(authenticated)/(app)/app/keys/CreateKey.tsx

Fix root key alert

---

apps/docs/mint.json
apps/docs/security.mdx

Adding security questions

---

apps/web/app/(authenticated)/(app)/app/[apiId]/keys/new/CreateKey.tsx
apps/web/app/(authenticated)/auth/sign-in/oauth-signin.tsx

Adds Meta to the form. 
Validates it 
This will close out #67

Adding meta input with JSON validation

---

apps/web/app/(landing)/pricing/page.tsx
apps/web/components/Navbar.tsx

Fixing pricing 
Adds my cal
Fix button in nav

Fixes menu and updates pricing

---

apps/web/app/(landing)/about/page.tsx
apps/web/app/(landing)/blog/[slug]/page.tsx
apps/web/app/(landing)/blog/page.tsx
apps/web/app/(landing)/changelog/[date]/page.tsx
apps/web/app/(landing)/changelog/page.tsx
apps/web/app/layout.tsx
apps/web/app/og/route.tsx
apps/web/middleware.ts

Generate our own OG images.

---

apps/api/pkg/server/key_create.go

Update status for create key with invalid key
Update status for create key invalid api

Chore: update status code for create key

---

apps/web/components/Navbar.tsx

Chore: Update navbar to have docs and also remove border

---

apps/api/pkg/server/key_create.go

Add check for DB and throw error based upon our delete keys error

Adding check for DB and throw error if not found

---

apps/docs/libraries/nuxt/overview.mdx

[nuxt][docs][fix] Update overview.mdx

---

apps/web/app/(landing)/pricing/page.tsx

Add volume discount to pro.
Add whitelist to enterprise
Update URL to my unkey Cal.com

Update Pricing page

---

.github/workflows/deploy-api.yaml
apps/api/fly.prod.toml

- This adds terms + privacy policy (#131)
- feat: use blue-green deployments
- feat: use blue-green deployments

deployments

---

apps/web/app/(authenticated)/(app)/app/TeamSwitcher.tsx
apps/web/app/(authenticated)/(app)/app/team/create/page.tsx
apps/web/app/(authenticated)/(app)/app/team/invite/page.tsx
apps/web/app/(authenticated)/(app)/app/team/page.tsx
apps/web/app/(authenticated)/auth/sign-in/email-signin.tsx
apps/web/app/(authenticated)/auth/sign-up/email-signup.tsx
apps/web/app/(landing)/pricing/page.tsx
apps/web/components/ui/select.tsx
apps/web/middleware.ts
apps/web/pages/api/v1/stripe/webhooks.ts

This PR introduces teams. 
- Handles invites via email 
- Handles auth via our custom flow using them
- Handles showing and hiding the invite if they aren't an admin
- Protects the entire app if they haven't paid for their bill by looking at their workspace plan 
This resolves #127

Introducing teams

---

apps/api/pkg/cache/cache_test.go
apps/api/pkg/database/conversion.go
apps/api/pkg/database/conversion_test.go
apps/api/pkg/database/interface.go
apps/api/pkg/database/key_decrement_remaining.go
apps/api/pkg/database/middleware/tracing.go
apps/api/pkg/database/models/key.xo.go
apps/api/pkg/entities/entities.go
apps/api/pkg/server/errors.go
apps/api/pkg/server/key_create.go
apps/api/pkg/server/key_create_test.go
apps/api/pkg/server/key_verify.go
apps/api/pkg/server/key_verify_test.go
apps/api/pkg/server/keys_list.go
apps/api/pkg/server/root_key_create_test.go
apps/api/pkg/server/server.go
apps/docs/api-reference/errors.mdx
apps/docs/api-reference/keys/create.mdx
apps/docs/api-reference/keys/verify.mdx
apps/docs/features/remaining.mdx
apps/docs/glossary.mdx
apps/docs/mint.json
apps/web/app/(landing)/policies/[slug]/page.tsx
apps/web/contentlayer.config.ts
packages/db/src/schema/keys.ts

- add Elixir supervision example (#136)
- Adding email changelog (#137)
- Add plausible (#138)
- Environments instead of hard code for plausible (#139)
- Fixing stripe being stuck on the payment screen (#141)
- Fix redirects to back from stripe
- feat: allow creating limited use keys by setting 'remaining'

limit usage

---

apps/docs/libraries/js/keys/create.mdx
packages/sdk/package.json
packages/sdk/src/index.ts

Adding remaining

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/doc_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/others.yml
.github/pull_request_template.yml

Added issue and pull request templates. ref #161

Issue and PR templates ref #161

---

apps/web/app/layout.tsx

Removes app/api* from our tracking.

KEY-66 : Exclude app/api* from tracking

---

apps/web/pages/api/v1/clerk/webhooks.ts

If the user is on the list don't error just fail with a 201 to satisfy Clerk

Add a check for already on the lists

---

apps/web/components/dashboard/page-header.tsx

This PR fixes overflow in actions header when using mobile. 

KEY-79 : Adds flex wrap to acitons

---

apps/docs/libraries/py/services/keys.mdx

This PR fixes the following issues:
Adds the new update key endpoint to the python sdk docs.

Add update key to python sdk docs

---

apps/docs/libraries/ex/functions/create_key.mdx
apps/docs/libraries/ex/functions/update_key.mdx
apps/docs/mint.json

Closes #186
This PR fixes the following issues:
- out of date Elixir SDK Docs
Here comes all the changes proposed through this PR
[x] - Updated docs 
- [x ] My change requires a change to the documentation.

Resolve "[KEY-80] [docs] Update Elixir Documentation & SDK"

---

apps/web/app/(authenticated)/(app)/app/[apiId]/delete-api-button.tsx
apps/web/app/(authenticated)/(app)/app/mobile-sidebar.tsx
apps/web/app/(authenticated)/(app)/app/team/invite/page.tsx
apps/web/app/(authenticated)/(app)/onboarding/client.tsx
apps/web/app/(authenticated)/auth/sign-in/email-signin.tsx
apps/web/app/(authenticated)/auth/sign-up/email-signup.tsx
apps/web/app/layout.tsx
apps/web/components/dashboard/api-key-table/table.tsx
apps/web/components/dashboard/charts.tsx
apps/web/pages/api/trpc/[trpc].ts

[KEY-72 /auth/sign-in : window is not defined](https://linear.app/unkey/issue/KEY-72/authsign-in-window-is-not-defined)
[KEY-73 og metadata](https://linear.app/unkey/issue/KEY-73/og-metadata)
[KEY-69 Duplicate workspace slug error message](https://linear.app/unkey/issue/KEY-69/duplicate-workspace-slug-error-message)
[KEY-84 Organization membership doesn't work](https://linear.app/unkey/issue/KEY-84/organization-membership-doesnt-work)
[KEY-82 Mobile menu doesn't close](https://linear.app/unkey/issue/KEY-82/mobile-menu-doesnt-close)
[KEY-81 Dark mode charts usage isn't color inverted](https://linear.app/unkey/issue/KEY-81/dark-mode-charts-usage-isnt-color-inverted)
[KEY-83 Revoke Selected Keys on mobile bleeds out the button](https://linear.app/unkey/issue/KEY-83/revoke-selected-keys-on-mob …

Many bug fixes

---

apps/docs/libraries/ex/overview.mdx

just updates elixir mix version

feat: update elixir version

---

apps/web/app/(authenticated)/(app)/app/[apiId]/create-key.tsx
apps/web/app/(authenticated)/(app)/app/team/create/page.tsx
apps/web/components/dashboard/api-key-table/table.tsx
apps/web/components/dashboard/charts.tsx
apps/web/lib/trpc/routers/workspace.ts
apps/web/pages/api/trpc/[trpc].ts

This fixes the following issues:
#195 
KEY-86
KEY-88

Web UI fixes

---

apps/docs/libraries/go/api/get.mdx
apps/docs/libraries/go/api/list.mdx
apps/docs/libraries/go/functions/create.mdx
apps/docs/libraries/go/functions/revoke.mdx
apps/docs/libraries/go/functions/update.mdx
apps/docs/libraries/go/functions/verify.mdx
apps/docs/libraries/go/overview.mdx
apps/docs/mint.json

This PR fixes the following issues: #192 
Added docs for the Go SDK client [unkey-go](https://github.com/WilfredAlmeida/unkey-go)

Go client docs

---

apps/web/app/(landing)/blog/[slug]/page.tsx
apps/web/app/(landing)/blog/page.tsx
apps/web/app/og/blog/route.tsx

This just adds the API to blog posts.

Adds OG API for blog posts.

---

apps/docs/api-reference/keys/verify.mdx

This PR fixes the following issues:
N/A
This PR is just a documentation update for the verify key endpoint, adding the missing `expires` fields to the response and also populating the response example  with all possible fields.

Improve docs for verify key

---

apps/web/app/(authenticated)/(app)/app/[apiId]/create-key.tsx
apps/web/app/(authenticated)/(app)/app/[apiId]/delete-api-button.tsx
apps/web/app/(authenticated)/(app)/app/keys/create-root-key-button.tsx
apps/web/app/(authenticated)/(app)/app/keys/page.tsx
apps/web/app/(authenticated)/(app)/app/team-switcher.tsx
apps/web/app/(landing)/about/page.tsx
apps/web/app/(landing)/blog/[slug]/page.tsx
apps/web/app/(landing)/changelog/[date]/page.tsx
apps/web/app/(landing)/page.tsx
apps/web/app/og/blog/route.tsx
apps/web/lib/trpc/routers/key.ts

1. Create key refreshes the route.
2. Delete API pushes users back to the home route.
3. Create root key refreshes the route.
This hides the temporary keys <1 minute for root keys that we create.
Use the full name instead of username as it's not guaranteed we have a user name for org switcher
The remaining option was missing from our UI, so it is now part of the creation form.
In the delete API we pushed the delete button right up against the input, now it has margins.

Fix: Dashboard improvements

---

apps/web/app/(authenticated)/(app)/app/[apiId]/create-key.tsx
apps/web/app/(authenticated)/(app)/app/[apiId]/delete-api-button.tsx
apps/web/app/(authenticated)/(app)/app/keys/create-root-key-button.tsx
apps/web/app/(authenticated)/(app)/app/keys/page.tsx
apps/web/app/(authenticated)/(app)/app/team-switcher.tsx
apps/web/app/(landing)/about/page.tsx
apps/web/app/(landing)/blog/[slug]/page.tsx
apps/web/app/(landing)/changelog/[date]/page.tsx
apps/web/app/(landing)/page.tsx
apps/web/app/og/blog/route.tsx
apps/web/lib/trpc/routers/key.ts

This forces the meta too format on blur. It does some of the #90, we aren't going to create an entire IDE for it.
#90

Meta formatting

---

packages/sdk/src/verify.ts

No issue yet.
#example
- Used a non-empty string for the token in verify.ts
Here comes all the changes proposed through this PR

Using a non-empty string for Unkey instantiation in verify.ts

---

apps/web/app/(authenticated)/(app)/app/keys/page.tsx
apps/web/app/(authenticated)/auth/sign-in/[[...sign-in]]/page.tsx
apps/web/app/(authenticated)/auth/sign-in/layout.tsx
apps/web/app/(authenticated)/auth/sign-up/[[...sign-up]]/page.tsx
apps/web/app/(authenticated)/auth/sign-up/layout.tsx
apps/web/app/(landing)/blog/[slug]/page.tsx
apps/web/app/(landing)/blog/page.tsx
apps/web/components/landing/page-links.tsx

This adds some text, fixes a few pieces of the flow.

Feat: sign up changes

---

apps/agent/pkg/server/key_update.go
apps/agent/pkg/server/key_update_multiple_times_test.go

- test: create test to reproduce
- fix: don't use cached value when updating a key

key 102 updating a key produces inconsistent results

---

apps/docs/libraries/rs/overview.mdx
apps/docs/mint.json

N/A
This PR adds the [Rust SDK](https://crates.io/crates/unkey) to the official docs.
N/A

Add rust sdk to docs

---

apps/web/app/(authenticated)/(app)/app/banner.tsx
apps/web/app/(authenticated)/(app)/app/layout.tsx
apps/web/components/banner.tsx
apps/web/lib/constants/quotas.ts
apps/web/lib/trpc/routers/workspace.ts
apps/web/pages/api/v1/cron/update-usage.ts
apps/web/pages/api/v1/stripe/webhooks.ts

- feat: update usage
- feat: show trial and exceede usage banners

trials and quotas

---

apps/web/app/(authenticated)/auth/sign-in/[[...sign-in]]/page.tsx
apps/web/app/(authenticated)/auth/sign-in/layout.tsx

Makes sign in a center login in white, with Sign In to Unkey

Update sign in

---

apps/web/app/(authenticated)/(app)/app/apis/client.tsx
apps/web/app/(authenticated)/(app)/app/team-switcher.tsx

Fixes #216 by updating the local state.

Update API if workspace changes.

---

apps/web/app/(authenticated)/auth/sign-up/email-signup.tsx

Fixes issue where onboarding is pushed instead of /app/apis

Fix redirect for orgs.

---

apps/web/middleware.ts

This stops infinite loops if the user has an org and no personal workspace

Fix onboarding flow for orgs.

---

apps/docs/mint.json
apps/web/app/(authenticated)/(app)/app/apis/[apiId]/keys/new/page.tsx
apps/web/app/(authenticated)/(app)/app/apis/[apiId]/keys/page.tsx
apps/web/app/(authenticated)/(app)/app/apis/[apiId]/layout.tsx
apps/web/app/(authenticated)/(app)/app/apis/[apiId]/page.tsx
apps/web/app/(authenticated)/(app)/app/apis/[apiId]/settings/page.tsx
apps/web/app/(authenticated)/(app)/app/apis/page.tsx
apps/web/app/(authenticated)/(app)/app/page.tsx
apps/web/app/(authenticated)/(app)/app/settings/general/page.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/page.tsx
apps/web/app/(authenticated)/(app)/app/settings/usage/page.tsx
apps/web/app/(authenticated)/(app)/app/settings/user/page.tsx
apps/web/app/(authenticated)/(app)/app/stripe/page.tsx
apps/web/app/(authenticated)/(app)/app/team-switcher.tsx
apps/web/app/(authenticated)/(app)/app/user-button.tsx
apps/web/app/(authenticated)/auth/sign-in/layout.tsx
apps/web/app/(authenticated)/auth/sign-up/email-code.tsx
apps/web/app/(authenticated)/auth/sign-up/oauth-signup.tsx
apps/web/app/(authenticated)/auth/sso-callback/[[...sso-callback]]/page.tsx
apps/web/app/(authenticated)/layout.tsx
apps/web/app/(landing)/devtools.fm/page.tsx
apps/web/lib/analytics.tsx
apps/web/middleware.ts
apps/web/next.config.js

Redirecting onboarding to new
This PR fixes the following issues:
#example
Here comes all the changes proposed through this PR

Onboarding is now new

---

apps/web/content/blog/ocr-service.mdx
apps/web/contentlayer.config.ts
apps/web/lib/trpc/context.ts
pnpm-lock.yaml

This fixes tables and GFM styling for our blog
Markdown tables are now supported.

fix: fixes tables to use GFM markdown style

---

apps/web/app/(landing)/page.tsx
apps/web/components/landing/newsletter.tsx
apps/web/components/ui/button.tsx
apps/web/package.json
apps/web/tailwind.config.js
pnpm-lock.yaml

This introduces a button to star us on GitHub and a five minute explaining how to use Unkey. This should improve both top of funnel and GH interest.

feat(homepage): adds GH button and video explaining Unkey

---

apps/web/app/(landing)/page.tsx

This adds a small paragraph that on us having realtime analytics for API and keys

chore(homepage): adds analytics to our features

---

apps/web/app/(authenticated)/(app)/app/user-button.tsx
apps/web/app/(authenticated)/auth/sign-up/email-signup.tsx

Our signup now requires first and last name... Our Userbutton will check for username, first and last name and finally email address

fix(email-signup user-button): signup requires first / lastname. Userbutton shows email as fallback

---

apps/web/app/(authenticated)/(app)/app/settings/root-keys/page.tsx
apps/web/components/dashboard/api-key-table/table.tsx
apps/web/components/dashboard/root-key-table/index.tsx
apps/web/components/dashboard/root-key-table/table.tsx
apps/web/lib/trpc/routers/key.ts
packages/sdk/src/client.ts

Root keys were unable to revoke due to the key being treated as a normal key. This allows deletion using a new internal route.

fix(root key revoke): this fixes root key revoke in the dashboard

---

.github/CONTRIBUTING.md

Was reading through the CONTRIBUTING.md and noticed some typos. Specifically `apps/api` should be `apps/agent`.
Closes #281

fix occurances of apps/api to be apps/agents

---

apps/docs/mint.json
apps/web/app/(landing)/oss-friends/page.tsx
apps/web/components/landing/social-media.tsx
apps/web/middleware.ts

OSS friends

---

apps/docs/features/analytics.mdx

fix(docs): typos in analytics page

---

apps/agent/cmd/agent/main.go
apps/agent/pkg/analytics/tinybird/tinybird.go
apps/agent/pkg/batch/consume.go
apps/agent/pkg/server/constants.go
apps/agent/pkg/server/server.go
apps/agent/pkg/server/v1_apis_remove.go

- feat: batch events before sending to tinybird
- fix: do nothing when the batch is empty
- style: formatting

key 139 batch tinybird ingestion

---

apps/web/app/(landing)/layout.tsx
apps/web/styles/blog/code.css

Styles the headings to codeblocks if they have titles.

fix(blog changelog): adds headings to codeblocks if they have titles

---

packages/sdk/src/client.ts

Adds ownerId to the returned types for listkeys

fix(client.ts): fixes types to correctly show that ownerId could be returned

---

.changeset/tricky-eggs-shake.md
.github/workflows/changesets.yaml

- chore(deps): remove changeset file for "@unkey/db" package and bump mysql2 version
- fix(changesets.yaml): update GITHUB_TOKEN secret to CHANGESETS_GITHUB_TOKEN

changesets token

---

apps/web/content/blog/secure-supabase-functions-using-unkey.mdx
examples/supabase-functions/supabase/functions/hello-world/index.ts

Adds Supabase secure with Unkey post.

Secure Supabase with Unkey

---

apps/web/styles/tailwind/tailwind.css

- [X ] 🐛 Bug fix
CSS to make our titles look nice.
Fixes [KEY-151]

[KEY-151] fix(codeblock titles): adds CSS to handle codeblock titles

---

apps/web/app/(authenticated)/(app)/app/desktop-sidebar.tsx
apps/web/app/(authenticated)/(app)/app/mobile-sidebar.tsx

bug(Sidebar) [KEY-155] - Fix Next Error on navigation

---

apps/web/app/(authenticated)/(app)/app/settings/user/update-user-name.tsx
apps/web/components/dashboard/copy-button.tsx
apps/web/pages/api/v1/stripe/webhooks.ts
internal/loops/src/index.ts

Fixes a number of bugs in the UI

---

internal/loops/src/index.ts

fix(loops): fix loops sending

---

apps/web/middleware.ts
pnpm-lock.yaml

Change middleware

---

apps/web/app/(authenticated)/(app)/app/keys/[keyId]/page.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/[keyId]/page.tsx
apps/web/lib/tinybird.ts

This is just a patch so pages don't error

fix(temp fix for analytics): this just patches so the page doesn't error

---

packages/api/package.json
packages/hono/package.json
packages/nextjs/package.json
packages/nuxt/package.json

fix: fixes our package publish issue

---

apps/agent/go.mod
apps/agent/go.sum

chore: update agent dependencies

---

pnpm-lock.yaml

chore: update all dependencies

---

apps/web/app/(authenticated)/(app)/app/keys/[keyId]/page.tsx
apps/web/app/(authenticated)/(app)/app/keys/[keyId]/table.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/[keyId]/access-table.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/[keyId]/page.tsx

feat: mask ips by default

---

apps/web/app/(authenticated)/(app)/app/keys/[keyId]/page.tsx
apps/web/app/(authenticated)/(app)/app/keys/[keyId]/table.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/[keyId]/access-table.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/[keyId]/page.tsx
apps/web/lib/tinybird.ts
internal/tinybird/pipes/endpoint__get_latest_verifications.pipe

latest-verifications

---

.github/workflows/ci.yaml
.github/workflows/tinybird_cd.yml
apps/web/lib/tinybird.ts

fix(tinybird.ts): update pipe name from "endpoint__get_latest_verifications__v1" to "endpoint__get_latest_verifications__v2"

---

packages/api/src/client.ts

fixes package incorrectly using api instead of apis.

---

packages/api/package.json
packages/api/src/client.ts

Fix package

---

apps/web/app/(authenticated)/(app)/app/apis/[apiId]/create-key.tsx

This allows users to see an error in our form and disables creations until they fix it. 
https://linear.app/unkey/issue/KEY-188/creating-a-key-with-expiration-in-the-past-errors

key-188 creating-a-key-with-expiration-in-the-past-errors

---

apps/web/app/(authenticated)/(app)/app/apis/[apiId]/create-key.tsx
apps/web/app/(authenticated)/(app)/app/stripe/page.tsx
apps/web/components/dashboard/command-menu.tsx
apps/web/middleware.ts

Custom Meta Formats, Remove last of .log instead of error, Clerk Middleware made good.

---

apps/web/app/(authenticated)/(app)/app/desktop-sidebar.tsx
apps/web/app/(authenticated)/(app)/app/team-switcher.tsx
apps/web/components/ui/dropdown-menu.tsx

Added truncation to TeamSwitcher component. Showing Ellipsis when truncated. Also showing tooltip on hover. 
Key-187

fix(team switcher): added truncation and tooltip to Teamswitcher

---

apps/web/app/(landing)/page.tsx
apps/web/lib/tinybird.ts

fix(tinybird.ts): change pipe name from "all_verifications__v1" to "endpoint__all_verifications__v1" and change property name from "count()" to "verifications" in the data object

fix(page.tsx): change property name from "count()" to "verifications" in the reduce function

---

apps/web/app/roadmap/page.tsx

Added a new folder /roadmap and page with redirect
key228
Added /roadmap folder with redirect page inside.

feat(roadmap): new roadmap redirect

---

apps/web/app/(landing)/oss-friends/page.tsx

This adds the real OSSFriends to our site

KEY-230 feat(ossfriends): adds the real OSSFriends to our site

---

apps/web/app/(landing)/page.tsx

Adds a little of what we do to opening paragraph

Update hero copy

---

apps/web/components/landing/social-media.tsx

style(twitter icon): changed icon to X

---

apps/web/app/(authenticated)/(app)/app/settings/general/page.tsx

Key-226
Added transparent background on hover

fix(copy button): change on hover to bg transparent

---

apps/web/app/(authenticated)/auth/sign-up/email-signup.tsx

KEY-235 fix(signup email input): fixed useEffect

---

apps/web/app/(landing)/blog/[slug]/page.tsx

Added a scroll area and bar to TOC for individual blogs
KEY-225
Added scrolling functionality to the Blog TOC

fix(blog toc): scroll bar to blog toc

---

apps/web/components/landing/footer.tsx

Added a documentation link in the footer links list
KEY-326
Added docs link to footer nav array

KEY-236 feat(footer): added documentation link in footer

---

examples/bun-server/Dockerfile
examples/bun-server/server.ts

rename Bun example `index.ts`/`server.ts` to comply with doc filename
log port on startup
add Dockerfile

Improve Bun example

---

apps/web/app/(authenticated)/(app)/app/banner.tsx
apps/web/middleware.ts

Fix middleware

---

.github/CONTRIBUTING.md

chore: fix typo in readme

---

.github/CONTRIBUTING.md
apps/web/lib/analytics.tsx
apps/web/lib/env.ts
apps/web/lib/tinybird.ts
apps/web/package.json
pnpm-lock.yaml

- feat: use noop tinybird when token is not provided
- docs(CONTRIBUTING.md): add instructions for adding tinybird auth token

make tinybird optional

---

apps/web/components/dashboard/navbar.tsx

fix: make dashboard navbar responsive

---

.husky/pre-commit
apps/web/app/(landing)/blog/[slug]/page.tsx
apps/web/contentlayer.config.ts
package.json
pnpm-lock.yaml

chore: init husky on fresh setup

---

apps/web/app/(landing)/blog/[slug]/page.tsx
apps/web/components/dashboard/navbar.tsx
apps/web/contentlayer.config.ts

chore: fix missing key warning

---

apps/web/app/(authenticated)/(app)/app/desktop-sidebar.tsx

fix: sidebar active state

---

apps/docs/contributing/editor-setup.mdx
apps/docs/mint.json
apps/docs/package.json

docs: Add editor setup

---

apps/agent/.env.example

fixed: merge conflicts for .env.example file in agent apps.

fix: merge conflicts in env.example file

---

.github/CONTRIBUTING.md

Added instructions to let users set Database values like DATABASE_HOST, DATABASE_USERNAME, etc.

Update Database values in documentation

---

.github/CONTRIBUTING.md
apps/agent/.env.example
apps/docs/contributing/getting-started.mdx
apps/web/.env.example

Adds more details and improves the guides overall, also makes the .env more clear.

Improves Contribution Guides

---

apps/web/app/(authenticated)/(app)/new/keys.tsx

https://github.com/unkeyed/unkey/issues/502

improve: make alert more visible

---

apps/web/app/(authenticated)/(app)/app/apis/[apiId]/create-key.tsx
apps/web/lib/trpc/routers/key.ts
internal/resend/.gitignore

Fixed the error validation "Expected number, received nan" in create key page
https://github.com/unkeyed/unkey/issues/505

fix: for error validation of number field

---

apps/web/app/(authenticated)/(app)/new/keys.tsx

Updated the alert sub text for more correct information.
https://github.com/unkeyed/unkey/issues/502

fix: sub title for alert

---

apps/docs/quickstart/nextjs.mdx

This fixes the typo on line 100 of the docs:
```diff
- The `withUnkey` wrapper takes a configuration object sa second optional argument to configure the request handling.
+ The `withUnkey` wrapper takes a configuration object as a second optional argument to configure the request handling.
```
closes #543

docs: fix typo

---

.github/workflows/semantic-pull-requests.yml

Forces PRs to follow conventional commits.

Feature: Create semantic-pull-requests.yml

---

apps/web/app/(landing)/careers/[slug]/page.tsx
apps/web/app/(landing)/careers/page.tsx
apps/web/content/jobs/software-engineer.mdx

This removes the current active role and also adds a redirect to the careers page if it doesn't exist

chore(careers): adds redirect to careers, removes our role

---

package.json

add biome linting to lint-staged command

feat: add linting to lint staged

---

apps/docs/libraries/springboot-java/api/get.mdx
apps/docs/libraries/springboot-java/api/list.mdx
apps/docs/libraries/springboot-java/functions/create.mdx
apps/docs/libraries/springboot-java/functions/revoke.mdx
apps/docs/libraries/springboot-java/functions/update.mdx
apps/docs/libraries/springboot-java/functions/verify.mdx
apps/docs/libraries/springboot-java/overview.mdx
apps/docs/mint.json

Added usage instructions for [springboot sdk](https://github.com/shreyanshtomar/unkey-springboot-sdk)!

docs: added usage instructions for springboot sdk

---

apps/docs/contributing/getting-started.mdx
apps/docs/mint.json
apps/web/app/(landing)/careers/[slug]/page.tsx

docs: Adding more detail to our guide

---

apps/docs/quickstart/nextjs.mdx

Adds tabs to the run section to make it obvious to the user, that each runtime works differently. We don't want to repeat work so this satisfies the requirement.
#568

docs: Update docs to show tabs for running dev

---

examples/deno-server/README.md
examples/deno-server/server.ts

docs: add deno server example

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/doc_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md
README.md

docs: updating our contribution requirements

---

apps/web/components/landing/footer.tsx

This fixes any link in the footer to be a <a> tag and open in a new tab. This leads to a better overall experience as a user.
Fixes #579 
Click external links to make sure we open in a new tab and don't 404

fix: footer to use external links as <a> tag

---

apps/docs/contributing/getting-started.mdx

Moves the DB to one section, and adds more clarity to creating an org in the Clerk section
Fixes #578
N/A

docs(update contributing setup guide): moves DB for clarity

---

.github/CONTRIBUTING.md
apps/docs/libraries/ts/hono.mdx
apps/docs/libraries/ts/sdk/overview.mdx
apps/docs/quickstart/nextjs.mdx

Fixes #593 (issue)
- Test A
- Test B

docs: Update package installation instructions

---

apps/docs/contributing/getting-started.mdx

docs: video walkthrough of setting up for development

---

.github/workflows/ci.yaml
apps/api/src/routes/legacy_keys_verifyKey.test.ts
apps/api/src/routes/legacy_keys_verifyKey.ts
apps/api/src/worker.ts

feat: add legacy verify route

---

apps/docs/mint.json

Re-order the quickstart so that Next.js is the default – I think it's the most common
Updates the docs to make Next.js the default framework for quickstart
Visit /docs/introduction and check the framework ordering

chore: update mint.json to reorder frameworks

---

apps/web/app/(authenticated)/(app)/app/desktop-sidebar.tsx
apps/web/app/(authenticated)/(app)/app/team-switcher.tsx
apps/web/components/ui/dropdown-menu.tsx
apps/web/tailwind.config.js

Fix alignment and scroll area
Fixes #611 
- Log in and see the sidebar

fix: desktop sidebar

---

apps/web/app/(landing)/[...not-found]/page.tsx
apps/web/app/(landing)/page.tsx

Our homepage is dynamic, every time someone access the page it is forced to be dynamic at runtime.
key-294

fix: landing page to be dynamic to stop errors

---

apps/web/app/(authenticated)/(app)/app/user-button.tsx
apps/web/components/dashboard/navbar.tsx
apps/web/components/landing/newsletter.tsx
apps/web/content/blog/ocr-service.mdx
apps/web/content/blog/using-unkey-with-auth.mdx
apps/web/content/changelog/2023-07-02.mdx
apps/web/content/changelog/2023-07-21.mdx
apps/web/content/changelog/2023-08-25.mdx
apps/web/content/changelog/2023-09-29.mdx
apps/web/content/changelog/2023-11-03.mdx

Changed link text and added aria labels and fixed missing ul element
key-288
Creates more descriptive human readable links, Adds ul element that was missing and aria label to newsletter button
Make sure site still functions

fix: key-288 changed link text

---

apps/web/components/landing/newsletter.tsx

key-289
Added label to conform to a11y standards
key-289
Make sure newsletter input works as it should and still looks fine.

fix: key-289 added label to newsletter input

---

apps/web/pages/api/v1/cron/update-usage.ts
internal/tinybird/pipes/aggregate_active_keys_hourly_by_workspace.pipe

chore(pipes): update version number to 3 and change datasource name
- Test A
- Test B

fix: pipe version

---

internal/tinybird/datasources/mv__monthly_active_keys.datasource
internal/tinybird/datasources/mv__monthly_verifications.datasource
internal/tinybird/pipes/aggregate_active_keys_monthly_by_workspace.pipe
internal/tinybird/pipes/aggregate_verifications_monthly_by_workspace.pipe

feat: add materialized views

---

apps/web/app/(landing)/changelog/page.tsx
apps/web/content/changelog/2023-12-01.mdx
apps/web/contentlayer.config.ts

chore: Changelog 12 01

---

apps/web/app/(authenticated)/(app)/new/create-api.tsx

fix: Adds posthog to create-api to identify earlier in the flow

---

apps/docs/mint.json
apps/web/app/(landing)/blog/[slug]/opengraph-image.tsx
apps/web/app/(landing)/blog/[slug]/page.tsx
apps/web/app/(landing)/blog/[slug]/twitter-image.tsx
apps/web/app/(landing)/careers/[slug]/opengraph-image.tsx
apps/web/app/(landing)/careers/[slug]/page.tsx
apps/web/app/(landing)/careers/[slug]/twitter-image.tsx
apps/web/app/(landing)/changelog/[date]/opengraph-image.tsx
apps/web/app/(landing)/changelog/[date]/page.tsx
apps/web/app/(landing)/changelog/[date]/twitter-image.tsx
apps/web/app/(landing)/templates/[slug]/opengraph-image.tsx
apps/web/app/(landing)/templates/[slug]/page.tsx
apps/web/app/(landing)/templates/[slug]/twitter-image.tsx

Moves Og images to co exist with their folder. This also has posthog added.
- Test A
- Test B

chore: Og image routes & Posthog for Mintlify

---

.github/workflows/ci.yaml
apps/api/src/pkg/keys/service.ts

- fix: add logs and catch error
- ci.yaml: remove unnecessary steps in the CI workflow

catch expiration bug

---

apps/api/package.json
apps/api/src/pkg/hono/app.ts
apps/api/tsconfig.json
apps/workflows/lib/db.ts
packages/api/package.json
packages/api/tsconfig.json
pnpm-lock.yaml

- fix: hide authorization header in v1/keys.verifyKey route
- chore: extend tsconfig from @unkey/tsconfig/base.json

chore: tsconfig

---

apps/api/src/routes/legacy_keys_verifyKey.test.ts

test: update status codes

---

apps/web/.infisical.json
apps/web/next.config.js

fix: Object freeze webpack

---

apps/api/src/routes/legacy_keys_verifyKey.test.ts

fix: Update legacy_keys_verifyKey.test.ts

---

apps/docs/libraries/py/overview.mdx
apps/docs/libraries/py/services/apis.mdx
apps/docs/libraries/py/services/keys.mdx

Updates documentation for the latest version of `unkey.py`.
Fixes #689
Ensure docs build.
`pnpm build` and `pnpm fmt` both failed for me but the areas affected are out of the scope of this PR.

docs: Update python SDK docs

---

apps/web/app/(authenticated)/(app)/app/apis/[apiId]/layout.tsx
apps/web/components/dashboard/create-key-button.tsx

key-315
Added component for CreateKeyButton to be used in layout file
make sure adding a new key still functions on web.

fix: key-315 added createKeyButton component to fix UI bug

---

apps/web/app/(authenticated)/(app)/app/team-switcher.tsx
apps/web/app/(authenticated)/(app)/integrations/vercel/callback/workspace.tsx

Should fix #703 
- Test A
- Test B

fix: Improve team switcher and remove the decremented Clerk feature

---

apps/api/src/routes/legacy_apis_createApi.ts
apps/api/src/routes/legacy_apis_deleteApi.ts
apps/api/src/routes/legacy_keys_createKey.ts
apps/api/src/routes/legacy_keys_deleteKey.ts
apps/api/src/routes/legacy_keys_updateKey.ts
apps/api/src/routes/v1_apis_createApi.ts
apps/api/src/routes/v1_apis_deleteApi.ts
apps/api/src/routes/v1_keys_createKey.ts
apps/api/src/routes/v1_keys_deleteKey.ts
apps/api/src/routes/v1_keys_updateKey.ts
apps/api/src/routes/v1_keys_updateRemaining.ts
internal/db/src/schema/audit.ts
pnpm-lock.yaml

All mutations through the API are now also audit logged
- Test A
- Test B

feat: log audit trails from api calls

---

apps/web/app/(authenticated)/(app)/app/apis/[apiId]/settings/delete-api.tsx

fix: 404 on deletion

---

apps/web/components/landing/footer.tsx

chore: Update analytics

---

apps/docs/libraries/ts/sdk/keys/create.mdx
apps/docs/libraries/ts/sdk/keys/update.mdx

docs(sdk/api): updated refill for sdk docs

---

apps/web/app/(authenticated)/(app)/app/settings/root-keys/create-root-key-button.tsx
apps/web/app/(authenticated)/(app)/new/keys.tsx

closes #726 
- Test A
- Test B

fix: Update example paths.

---

apps/web/app/(authenticated)/(app)/app/apis/[apiId]/create-key.tsx

Fix: Check to make sure refill has a value before check

---

apps/web/app/(authenticated)/(app)/app/team-switcher.tsx

One line fix in the tailwindcss classname for the `DropdownMenuContent`.
Demo:
https://github.com/unkeyed/unkey/assets/73758525/6bbe4aa1-e447-4301-8bd8-6fcf75ecfa6b
Fixes #734
- Run it locally
- Test opening and closing the dropdown for desktop view
- Test opening and closing the dropdown for mobile view

fix: dropdown container position

---

apps/docs/libraries/rs/overview.mdx

Updates the Rust SDK docs with more examples.
Fixes #745 
Spell check!!!!!!

docs: Update Rust SDK docs

---

apps/api/src/pkg/ratelimit/client.ts
apps/web/app/(authenticated)/(app)/app/apis/[apiId]/layout.tsx
apps/web/app/(authenticated)/(app)/app/apis/[apiId]/settings/page.tsx
apps/web/app/(authenticated)/(app)/app/keys/[keyId]/layout.tsx
apps/web/app/(authenticated)/(app)/app/keys/[keyId]/settings/page.tsx
apps/web/app/(authenticated)/(app)/app/settings/general/page.tsx
apps/web/components/dashboard/copy-button.tsx

- Update page.tsx(fixed hover overflow)
- chore: clean up CopyButton styles

fix: copy button hover styles

---

apps/web/app/(authenticated)/(app)/app/settings/user/update-user-email.tsx
apps/web/app/(authenticated)/(app)/app/settings/user/update-user-name.tsx
apps/web/components/dashboard/api-key-table/index.tsx
apps/web/components/dashboard/root-key-table/index.tsx
apps/web/lib/clerk.ts

- Surfaces two errors to the user that are currently swallowed (when inviting a user that already exists, and when choosng a username that's already taken)
- Adds an icon for the 'details' button when clicking on the 'see more' menu for an individual key or root key
- Fixes an issue with the [Radix UI dropdown](https://github.com/radix-ui/primitives/issues/1241) which sets pointer events to 'none' after it's closed
- Icons: /app/settings/root-keys,  /app/apis/[api]/keys
- Errors: /app/settings/user: adding existing user + choosing taken username will surface errors
- UI non-interactive: /app/settings/user: removing a user will not make UI non-interactive

fix: UI papercuts

---

apps/docs/mint.json

docs: Adds 429 to the menu

---

apps/web/app/(authenticated)/(app)/new/keys.tsx

This PR removes the * role that is inserted on creation. Which causes the duplicate insert error.
- Test A
- Test B

fix: Removes the * role which duplicates * roles.

---

apps/docs/libraries/ts/sdk/keys/delete.mdx

Discovered a small **typo in the docs** after upgrading to `@unkey/api@0.16.0`.
- Test A
- Test B

fix(docs): typo

---

apps/landing/app/blog/page.tsx
apps/landing/components/frame.tsx

New <Frame> component for blog
Eng 481
it looks ok

feat: blog frame component

---

apps/api/src/routes/legacy_apis_deleteApi.ts
apps/api/src/routes/legacy_apis_getApi.ts
apps/api/src/routes/legacy_keys_deleteKey.ts
apps/api/src/routes/v1_apis_createApi.ts
apps/api/src/routes/v1_apis_deleteApi.ts
apps/api/src/routes/v1_apis_getApi.ts
apps/api/src/routes/v1_apis_listKeys.ts
apps/api/src/routes/v1_keys_createKey.ts
apps/api/src/routes/v1_keys_deleteKey.ts
apps/api/src/routes/v1_keys_getKey.ts
apps/api/src/routes/v1_keys_getVerifications.ts
apps/api/src/routes/v1_keys_updateKey.ts
apps/api/src/routes/v1_keys_updateRemaining.ts
apps/web/app/(authenticated)/(app)/app/settings/root-keys/[keyId]/permissions/permissions.ts
apps/web/app/(authenticated)/(app)/app/settings/root-keys/[keyId]/permissions/workspace.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/new/client.tsx
internal/rbac/src/queries.ts

also finally make role evaluation typesafe, lol

feat: add new workspace scoped key roles

---

apps/landing/app/blog/page.tsx
apps/landing/components/blog-list.tsx
apps/landing/components/mdx-content.tsx
apps/landing/content/blog/how-unkey-treats-marketing.mdx
apps/landing/package.json
apps/landing/tailwind.config.ts
pnpm-lock.yaml

blog list and other blog setup stuff for landing
eng-478
More work might be needed once the rest of the blog is in place. List item was added and temp blog post for testing. 
- Test A
- Test B

feat: blog list component

---

apps/web/app/(landing)/page.tsx
apps/web/components/landing/numbers-served.tsx

fix: Stats suspense

---

apps/web/lib/auth.ts

fix: Redirect if signed out

---

apps/web/app/(authenticated)/(app)/app/apis/[apiId]/settings/delete-api.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/new/client.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/new/page.tsx
apps/web/app/(authenticated)/(app)/app/settings/root-keys/page.tsx
apps/web/components/dashboard/api-key-table/index.tsx
apps/web/components/dashboard/api-key-table/table.tsx
apps/web/components/dashboard/root-key-table/index.tsx
apps/web/components/dashboard/root-key-table/table.tsx

- Fixes #946 Which prevented unchecking the permissions on custom API while creating root-keys.
- Fixes #946 Which showed the deleted APIs while creating new root-keys.
- Enhances loading states while batch-deleting (checkboxes in table) root-keys and keys. 
- Bug A: Simply go to the new root-key creation form and try to the checkbox of an api (not the checkbox of the workspace but of the custom apis).
- Bug B: Create a new API and immediately delete it. Then try to create a new root-key and you will see that the deleted API is still there.

fix(web): root key creation checkbox state

---

apps/web/app/(landing)/page.tsx
apps/web/components/landing/numbers-served.tsx

- each component's data fetching is try-catched
- the component is wrapped in a suspense
- we log the results, for debugging once it crashes again
I hope this works

fix: separate stats into their own async component

---

apps/api/src/pkg/ratelimit/client.ts
apps/api/src/pkg/usagelimit/client.ts

sometimes the network just craps out, nothing you can do

fix: add 1 retry when calling a durable object

---

apps/landing/app/templates/page.tsx
apps/landing/components/button.tsx
apps/landing/components/svg/template-page.tsx
apps/landing/components/template/page-intro.tsx

template page intro
eng-543
components for template page intro and styling
Looks Like it should

feat(template page intro): component with intro for template page

---

apps/web/app/(authenticated)/(app)/app/keys/[keyAuthId]/[keyId]/permissions/chart.tsx
apps/web/app/(authenticated)/(app)/new/keys.tsx

fix: permissions chart layout

---

apps/api/src/pkg/errors/http.ts

- fix: return status 429 on ratelimits
- fix: status codes
- fix: status codes

fix: api status codes

---

apps/web/content/blog/building-authentic-comms.mdx

chore: Add authentic comms blog

---

apps/landing/app/changelog/changelog-grid-item.tsx
apps/landing/app/changelog/changelog-grid.tsx
apps/landing/app/changelog/page.tsx
apps/landing/app/changelog/side-list.tsx
apps/landing/components/changelog/mdx-content-changelog.tsx
apps/landing/components/svg/changelog.tsx
apps/landing/content/changelog/2023-06-25.mdx
apps/landing/content/changelog/2023-07-02.mdx
apps/landing/content/changelog/2023-07-03.mdx
apps/landing/content/changelog/2023-07-10.mdx
apps/landing/content/changelog/2023-07-21.mdx
apps/landing/content/changelog/2023-08-10.mdx
apps/landing/content/changelog/2023-08-25.mdx
apps/landing/content/changelog/2023-09-08.mdx
apps/landing/content/changelog/2023-09-29.mdx
apps/landing/content/changelog/2023-11-03.mdx
apps/landing/content/changelog/2023-12-01.mdx
apps/landing/content/changelog/2023-12-15.mdx
apps/landing/content/changelog/2024-01-05.mdx
apps/landing/content/changelog/2024-01-19.mdx

Changelog labels and refactoring for new layout
Eng-591
- Test A
- Test B

feat: add tags to changelogs frontmatter

---

.changeset/late-bugs-tie.md
packages/api/package.json

- [] Bug fix (non-breaking change which fixes an issue)
- Test A
- Test B

chore: bump version @unkey/api

---

apps/landing/app/blog/blog-image.tsx
apps/landing/app/changelog/changelog-grid-item.tsx
apps/landing/app/changelog/page.tsx
apps/landing/components/changelog/mdx-content-changelog.tsx

svg's and meteor changes for responsiveness
eng-613
- Test A
- Test B

fix: Changelog responsivenes and svgs

---

apps/landing/app/blog/page.tsx
apps/landing/app/changelog/changelog-grid-item.tsx
apps/landing/app/templates/[slug]/page.tsx
apps/landing/app/templates/page.tsx
apps/landing/components/footer/footer.tsx
apps/landing/components/svg/changelog.tsx
apps/landing/tailwind.config.ts

template page responsiveness
eng-615
- Test A
- Test B

fix: template pages svgs and responsiveness

---

apps/landing/app/templates/[slug]/page.tsx
apps/landing/app/templates/page.tsx
apps/landing/components/svg/changelog.tsx

svg fix
eng-616
Fixed positioning for background light scg
- Test A
- Test B

fix: padding for background light svgs

---

apps/landing/app/changelog/changelog-grid-item.tsx
apps/landing/app/changelog/page.tsx
apps/landing/app/globals.css
apps/landing/components/changelog/mdx-content-changelog.tsx

Fixed changelog for various screen sizes
eng-618
Changed margins for different screen sizes
- Test A
- Test B

fix: changelog padding changes

---

apps/web/app/(authenticated)/(app)/app/apis/page.tsx
apps/web/app/(authenticated)/(app)/app/banner.tsx
internal/resend/emails/subscription_ended.tsx

fix: billing links to go to settings/billing

---

apps/docs/security/root-keys.mdx

Adds docs with guidance on what to do in the event of a root key leak; GH requirement for secret scanning
Visit /docs/security/root-keys

feat: Add guidance on root key revocation for leaks

---

apps/web/app/(authenticated)/(app)/app/keys/[keyAuthId]/[keyId]/permissions/page.tsx

fix: force dynamic on keyAuth page.

---

apps/landing/app/globals.css
apps/landing/app/hero/hero-main-section.tsx
apps/landing/app/page.tsx
apps/landing/components/audit-logs-bento.tsx
apps/landing/components/audit/audit-logs.tsx
apps/landing/components/open-source.tsx

Fixes a couple of minor bugs and adds latest copy

feat: Landing fixes

---

apps/landing/app/blog/blog-image.tsx
apps/landing/components/mdx-content.tsx

- [] Bug fix (non-breaking change which fixes an issue)
- Test A
- Test B

chore(image frame for changelog): added image frame to img element

---

.changeset/afraid-dolphins-destroy.md
apps/docs/libraries/ts/ratelimit.mdx
packages/ratelimit/src/ratelimit.ts

- **docs: explain how to improve stability**
- **feat: add onError callback**

feat: ratelimit catch

---

apps/landing/app/blog/[slug]/page.tsx
apps/landing/lib/mdx-helper.ts

fix: Blog load improvements

---

apps/landing/app/about/page.tsx

Eng 719 
Does it look ok to you?

fix: about comets look massive

---

apps/landing/app/blog/[slug]/page.tsx
apps/landing/app/blog/page.tsx
apps/landing/components/frame.tsx

blog page max width
eng-743
Looks ok

fix(blog max width): added max width to blog pages

---

apps/web/app/(authenticated)/(app)/app/settings/billing/page.tsx

fix(web): add ratelimit usage estimation

---

apps/landing/app/blog/[slug]/page.tsx
apps/landing/app/blog/blog-authors.tsx
apps/landing/app/blog/page.tsx

blog sidebar
eng-726
- Test A
- Test B

fix(blog sidebar): made blog sidebar larger

---

apps/landing/app/blog/blogs-grid.tsx

blog
eng-738
- Test A
- Test B

fix(blog): added padding on smaller screens

---

apps/landing/app/pricing/components.tsx

fixed width on icons
eng-876
- Test A
- Test B

fix(pricing): pricing icons

---

apps/landing/app/templates/client.tsx
apps/landing/components/blog/blog-hero.tsx
apps/landing/components/blog/blogs-grid.tsx
apps/landing/components/frame.tsx

blog
eng-861
- Test A
- Test B

fix(blog tags): fixed meteors passing over tags and frame

---

apps/landing/components/blog/blog-code-block.tsx
apps/landing/components/blog/blog-list.tsx
apps/landing/components/changelog/changelog-grid-item.tsx
apps/landing/components/x-share-button.tsx
apps/landing/content/changelog/2023-11-03.mdx
apps/landing/content/changelog/2023-12-01.mdx
apps/landing/content/changelog/2024-01-05.mdx
apps/web/content/changelog/2023-11-03.mdx
apps/web/content/changelog/2024-01-05.mdx

Fixes: ENG-849, ENG-850, ENG-852, ENG-853, ENG-854, ENG-855, ENG-856
- Test A
- Test B

fix: Changelog fixes

---

apps/landing/app/blog/[slug]/page.tsx
apps/landing/app/blog/page.tsx
apps/landing/components/blog/blog-hero.tsx
apps/landing/contentlayer.config.ts
apps/landing/package.json
pnpm-lock.yaml

- **style(blog-hero.tsx): improve responsiveness and alignment of blog hero component**
- **fix(blog): fix regex pattern in contentlayer.config.ts for detecting headings**

feat(eng 867): blog TOC

---

apps/landing/app/discord/page.tsx
apps/landing/app/github/page.tsx
apps/landing/components/footer/footer.tsx
apps/landing/components/navbar/navigation.tsx

- **feat: add github and discord links**
- **refactor(footer.tsx): add 'external' property to NavLink type feat(footer.tsx): update external links to open in new tab and add noreferrer feat(footer.tsx): update internal links to not open in new tab**

eng 884 add github link in navbar

---

apps/landing/components/blog/blogs-grid.tsx

Blog Cards
eng-862
It matches figma. Not sure if it looks to thin or not personally

style(blog cards): change spacing for blog cards

---

apps/landing/components/blog/blogs-grid.tsx

blog tags
eng-858
- Test A
- Test B

fix(blog tag links): blog tag links no scroll added

---

apps/landing/contentlayer.config.ts
pnpm-lock.yaml

fix: Add git style markdown so tables work

---

apps/landing/next.config.js

Fixes ENG-882
- Test A
- Test B

chore: Redirect changelog from /changelog/ to changelog#

---

apps/docs/integrations/vercel.mdx
apps/landing/content/blog/introducing-vercel-integration.mdx
apps/landing/content/changelog/2023-12-01.mdx
apps/landing/package.json
apps/landing/tailwind.config.ts
apps/web/content/blog/introducing-vercel-integration.mdx
apps/web/content/changelog/2023-12-01.mdx
pnpm-lock.yaml

fix: Adds aspect ratio to YT iframes

---

apps/landing/app/blog/page.tsx
apps/landing/components/blog/blog-hero.tsx

blog
eng-860
- Test A
- Test B

fix(blog feature article): aligned article

---

apps/landing/app/blog/[slug]/page.tsx
apps/landing/app/blog/page.tsx
apps/landing/components/blog/blog-hero.tsx
apps/landing/components/blog/blogs-grid.tsx

blog
eng-873
- Test A
- Test B

fix(blog slug hero): fixed alignment for blog hero

---

apps/landing/app/blog/page.tsx
apps/landing/components/blog/blog-hero.tsx

blog
eng-859
- Test A
- Test B

fix(blog feature): blog feature alignment

---

apps/landing/app/about/page.tsx

about
eng-819
- Test A
- Test B

fix(about page investors): modified investors padding and orientation

---

apps/landing/app/templates/[slug]/page.tsx
apps/landing/app/templates/client.tsx
apps/landing/components/template/codeblock.tsx
apps/landing/components/template/mdx-components.tsx

Fixes  ENG-831
- Test A
- Test B

fix: template codeblocks and highlights ENG-831

---

apps/landing/app/about/page.tsx
apps/landing/app/code-examples.tsx
apps/landing/components/open-source.tsx
apps/landing/components/svg/star-dots.tsx
apps/landing/components/ui/meteorLines.tsx
apps/landing/tailwind.config.ts

eng-807, eng-816, eng-791, eng-792
adjusts styling of meteors on about page, other minor styling updates

fix: about visual fixes

---

apps/landing/components/mdx-content.tsx

Fix: scroll offset

---

apps/landing/app/blog/[slug]/page.tsx

breadcrumb links
eng-905
- Test A
- Test B

fix(blog breadcrum links): added links to breadcrumbs

---

apps/landing/components/blog/blogs-grid.tsx

alignment of button text
eng-903
- Test A
- Test B

fix(blog tags): blog tag button text

---

apps/landing/app/about/page.tsx

feat: add values to about page

---

apps/web/content/blog/uuid-ux.mdx

Fixed a typo. Really good blog!
Skipping this to reduce noise, let me know if I should do it anyway. Should this be a chore?
A proofread should be good enough

fix: typo in uuid blog

---

apps/landing/app/about/page.tsx

removes icons from /about values section

fix: remove values icons

---

apps/api/src/pkg/cache/zone.ts
apps/api/src/pkg/logging/index.ts
apps/api/src/pkg/logging/logdrain.ts
apps/api/src/pkg/usagelimit/durable_object.ts
apps/logdrainv2/src/worker.ts

- **feat: console logdrain**
- **refactor(logging): replace ConsoleLogger with LogdrainLogger in durable_object.ts feat(logging): add LogdrainLogger import in logging/index.ts**

feat: logdrain console

---

apps/landing/app/about/page.tsx

chore: Add some copy that makes sense for the about page

---

apps/landing/app/pricing/discover.tsx

pricing can now be custom with max ratelimit
eng-917
- Test A
- Test B

fix(pricing page): max range shows custom for ratelimit

---

apps/landing/components/blog/blogs-grid.tsx

fixed pill size when selected
eng-923
- Test A
- Test B

fix(blog pills): set font size to be same for selected or not

---

apps/landing/app/oss-friends/page.tsx

oss friends
eng-925
- Test A
- Test B

feat: oss friends page for footer link

---

apps/landing/components/stat-list.tsx
apps/landing/components/stats.tsx

fix(stats): add gap and padding

---

apps/landing/app/blog/page.tsx
apps/landing/components/blog/blog-card.tsx
apps/landing/components/blog/blogs-grid.tsx
apps/landing/content/blog/unkey-raises-1-5-million.mdx

fix: Blog cards and image height

---

apps/landing/app/blog/[slug]/page.tsx

fix: copy and author spacing

---

apps/landing/app/blog/[slug]/page.tsx
apps/landing/components/blog/blog-quote.tsx

fixed a thing
eng-956
- Test A
- Test B

fix(blog): blog code block spacing again

---

apps/landing/app/code-examples.tsx

https://github.com/unkeyed/unkey/assets/18246773/267c6bb7-ab68-4148-976b-e6dd7d2b83da

fix: reduce height of comets

---

apps/landing/app/hero/hero-main-section.tsx
apps/landing/components/button.tsx

chore(landing/hero): decrease heading line height and increase contrast between heading and subheading

---

apps/landing/app/page.tsx

…top of landing
landing
eng-912
- Test A
- Test B

fix: modified desktop background image for landing

---

apps/landing/components/analytics/analytics-bento.tsx

https://github.com/unkeyed/unkey/assets/10366880/caf446fc-2202-44dd-a60f-9e192598cb04

landing: ensure consistent padstart on the code editor

---

apps/landing/components/blog/blog-hero.tsx

Reduce border with of the blog hero

fix: reduce blog hero border width

---

apps/landing/components/cta.tsx

landing cta
eng-962
- Test A
- Test B

fix(cta): add overflow hidden to hide svg overflow

---

apps/landing/app/about/page.tsx

fix: reduce padding of values on mobile

---

apps/landing/components/footer/footer.tsx

landing: fix typo for X social in footer

---

apps/landing/components/cta.tsx
apps/landing/components/section.tsx

fix(cta): balance footer

---

apps/landing/app/code-examples.tsx
apps/landing/app/hero/hero-main-section.tsx
apps/landing/app/page.tsx
apps/landing/components/analytics/analytics-bento.tsx
apps/landing/components/button.tsx
apps/landing/components/cta.tsx
apps/landing/components/navbar/navigation.tsx
apps/landing/tailwind.config.ts

https://github.com/unkeyed/unkey/assets/10366880/8f337fd3-40eb-45e8-93cd-7fcf8203aac8

fix: landing: add shiny hover to cta

---

apps/landing/content/blog/introducing-ratelimiting.mdx

fix: Add post so our button works

---

apps/landing/components/rate-limits-bento.tsx

fix(landing): bento spacing fixed on md and lg screens

---

apps/landing/app/about/page.tsx
apps/landing/app/blog/[slug]/page.tsx
apps/landing/app/code-examples.tsx
apps/landing/app/pricing/components.tsx
apps/landing/app/pricing/discover.tsx
apps/landing/app/pricing/page.tsx
apps/landing/app/templates/[slug]/page.tsx
apps/landing/app/templates/client.tsx
apps/landing/components/blog/blog-card.tsx
apps/landing/components/blog/blog-code-block.tsx
apps/landing/components/blog/blog-hero.tsx
apps/landing/components/blog/suggested-blogs.tsx
apps/landing/components/button.tsx
apps/landing/components/copy-button.tsx
apps/landing/components/footer/footer.tsx
apps/landing/components/footer/wordmark.tsx
apps/landing/components/mdx-content.tsx
apps/landing/components/navbar/navigation.tsx
apps/landing/components/stat-list.tsx
apps/landing/components/template/codeblock.tsx
apps/landing/components/template/mdx-components.tsx
pnpm-lock.yaml

Fixed a bunch of a11y violations across all pages
a11y lighthouse scores:
```
/: 76 -> 95
/about: 86 -> 100
/blog: 95 ->100
/blog/[slug]: 91 -> 100
/pricing: 86 -> 100
/changelog: 90 -> 100
/templates: 94 -> 100
/templates/[slug]: 80 -> 94
```

fix: a11y violations

---

apps/landing/components/audit/command.tsx

fix(bento select): landing

---

apps/dashboard/app/auth/sign-up/email-signup.tsx

fix: Make clerk sign up for emails work again

---

apps/dashboard/app/auth/layout.tsx

fix: Update image url for auth page

---

apps/docs/contributing/getting-started.mdx

fix: typo in getting-started

---

apps/api/package.json
apps/api/src/pkg/analytics.ts
apps/api/src/pkg/env.ts
apps/api/src/pkg/middleware/init.ts
apps/api/src/pkg/middleware/metrics.ts
pnpm-lock.yaml

- **feat: prepare for clickhoues logging**
- **feat(env.ts): add CLICKHOUSE_HOST, CLICKHOUSE_USERNAME, and CLICKHOUSE_PASSWORD feat(init.ts): update initialization of Analytics with clickhouse configuration**

feat: try clickhouse

---

apps/www/app/about/page.tsx

fix(about): deduplicate grid/table border

---

apps/www/app/code-examples.tsx

fix(landing): gradient underneath the code editor

---

apps/www/components/border.tsx
apps/www/components/stat-list.tsx

fix(landing): remove additional border of stat

---

apps/www/components/button.tsx

chore(landing): add bg color to badge

---

apps/www/app/globals.css
apps/www/app/hero.tsx
apps/www/components/youtube-embed.tsx

fix(landing): center lower part of mainboard

---

apps/dashboard/app/auth/sign-up/email-signup.tsx

fix: Fix loading state for clerk

---

apps/www/app/(not-found)/components/spotlight.tsx
apps/www/app/not-found.tsx
apps/www/components/button.tsx
apps/www/tailwind.config.ts

adds 404 for www
https://github.com/unkeyed/unkey/assets/10366880/0b742af0-b2b3-4796-bff0-8199d6ba29b4

feat(www): add 404 page

---

apps/www/app/(not-found)/components/spotlight.tsx
apps/www/app/not-found.tsx

just polishing the first iteration
https://github.com/unkeyed/unkey/assets/10366880/92032174-05f6-4574-8ff6-44a51e945cc8

chore(www): polish 404 first iteration

---

apps/www/app/code-examples.tsx

-  adjust focus on code tabs 
https://github.com/unkeyed/unkey/assets/56942108/d556b24a-d1e8-4c87-999f-8c83d5d85789
- component separation to avoid component recreation
- addition of map to improve component scalability and facilitate maintenance
Fixes #1544

fix: adjust focus on code tabs and improve component

---

apps/www/app/globals.css
apps/www/components/stat-list.tsx

bef
aft
still clipping stats so will resolve that in another PR

chore(landing): reduce extreme gradient transition on stats

---

apps/www/components/blog/blog-card.tsx
apps/www/components/blog/blog-hero.tsx
apps/www/components/blog/blog-list.tsx
apps/www/components/blog/blogs-grid.tsx

- I added hover effect to blog cards
- blog card alignment adjustment
https://github.com/unkeyed/unkey/assets/56942108/1d339fae-900f-4a2b-9647-9f5d8470d1fc
https://github.com/unkeyed/unkey/assets/56942108/e1bf06aa-ae12-4b2e-8eaf-da7e15213186
-------------------------
Fixes #1601

fix: adding hover to blog card and adjusting alignments

---

apps/www/components/analytics/analytics-bento.tsx

fix(landing): adjust realtime analytics section alignment

---

apps/www/providers/posthog/PostHogPageView.tsx

chore: Add pageleave for web anaylytics

---

.github/workflows/deploy.yaml

ci: remove af-south-1

---

apps/www/components/navbar/navigation.tsx
tools/local/src/db.ts

Computes the scroll percentage on the mount of the navbar so that the opacity is added accordingly. 
Fixes #1630 
- Visit the landing page, scroll down a little, and click the "Get started" button. Navigate back to the landing page using the browser back button. Overlapping should not be observed.

fix: main section content overlapping navbar on navigating back to landing page

---

.changeset/lovely-emus-mix.md
.github/workflows/deploy.yaml
apps/api/src/integration/keys_updated_at_actually_updates.ts
apps/api/src/pkg/testutil/request.ts
apps/api/src/routes/schema.ts
apps/api/src/routes/v1_ratelimit_limit.accuracy.test.ts
apps/docs/api-reference/apis/list-keys.mdx
apps/docs/api-reference/keys/get.mdx
packages/api/src/openapi.d.ts

- **feat: return updatedAt in sdk**
- **fix(api): update createdAt field schema to be required and remove optional feat(api): add updatedAt field when retrieving keys docs(api): update openapi definition for createdAt field to be required**

feat: add updateAt in sdk

---

apps/api/src/pkg/cache/namespaces.ts
apps/api/src/pkg/keys/service.ts
apps/api/src/routes/v1_apis_listKeys.ts
apps/api/src/routes/v1_keys_deleteKey.ts
apps/api/src/routes/v1_keys_getKey.ts
apps/api/src/routes/v1_keys_getVerifications.ts
apps/api/src/routes/v1_migrations_createKey.ts
internal/db/src/schema/keys.ts
internal/db/src/types.ts
packages/cache/src/stores/cloudflare.ts

- **fix: encryption schema**
- **fix(cloudflare.ts): update default cacheBuster value from "v2" to "v1"**

fix: encryption schema

---

apps/docs/ratelimiting/introduction.mdx

docs: fix root key creation url

---

.changeset/twelve-buckets-beam.md
apps/api/src/routes/v1_keys_createKey.happy.test.ts
apps/api/src/routes/v1_keys_createKey.ts

- **feat(api): add support for specifying permissions when creating a key**
- **chore(changeset): bump "@unkey/api" package to patch version feat(changeset): allow adding permissions when creating keys**

feat: create keys with permissions

---

apps/docs/migrations/keys.mdx

Fixes #1696 
- Test A
- Test B

fix: add permission call out

---

apps/docs/libraries/nuxt/overview.mdx
apps/docs/libraries/ts/sdk/keys/create.mdx
apps/www/content/blog/ocr-service.mdx

Updates docs for creating keys with new rate limiting syntax. Also updates docs where old syntax is referenced
Visit the 'create key' section of the docs

fix: Update docs for rate limiting syntax change

---

__checks__/api.check.ts
__checks__/heartbeat.check.ts
__checks__/homepage.spec.ts
apps/api/__checks__/v1_liveness.check.ts
apps/api/src/pkg/db.ts
apps/api/src/pkg/middleware/init.ts
apps/api/src/pkg/ratelimit/durable_object.ts
checkly.config.ts
package.json
pnpm-lock.yaml

- **refactor(init.ts): increase database connection retry to 3**
- **fix(ratelimit): update error handling in DurableObjectRatelimiter**

eng 135 wrap all db reads with a retry

---

apps/api/src/pkg/ratelimit/client.ts
apps/api/src/routes/v1_keys_verifyKey.ts

- **refactor(v1_keys_verifyKey.ts): update permissions schema to support multiple permission query structures**
- **fix: break retries if successfully ratelimited**

permission query openapi

---

apps/play/app/globals.css
apps/play/app/layout.tsx
apps/play/app/page.tsx
apps/play/components/ui/terminalInput.tsx
apps/play/components/ui/textAnimator.tsx
apps/play/lib/data.ts

fix: style and minor changes

---

apps/docs/mint.json

fix: Fix Go SDK in sidebar

---

apps/docs/mint.json
apps/www/app/blog/page.tsx
apps/www/content/changelog/2024-03-01.mdx

Fixes ENG-1039
- Test A
- Test B

fix: ENG-1039 removes hero blog from grid results.

---

apps/docs/contributing/getting-started.mdx

Fixes #1739 
- Copy & run the github clone url

fix: correct gitHub clone URL to use HTTPS

---

apps/www/app/accelerate/page.tsx
apps/www/app/globals.css

This PR improves readability of the website heading/text gradients from 0.3 to 0.6 in alpha layer.
Before:
After:
- Test A
- Test B

chore(www): improve readability for 0.3 alpha gradients (change to 0.6)

---

apps/dashboard/app/(app)/audit/[bucket]/page.tsx
apps/dashboard/lib/trpc/routers/workspace/optIntoBeta.ts
internal/db/src/schema/workspaces.ts
pnpm-lock.yaml

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjZjNjExM2ExZGE1ZmQ5NmY4M2RiZjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.bNjNVEo9RWnqYttaYVbgXEJ_91TbSNfTGUc0VQDa-Lc">Huly&reg;: <b>ENG-1748</b></a></sub>

chore: change default audit log retention days to 30 if not specified

---

apps/dashboard/app/(app)/ratelimits/[namespaceId]/page.tsx

Fixes gird columns on mobile
**Before**:
Ipad
**Iphone**
**Macbook pro 15**
After:
**Ipad**
**Iphone**
**Macbook pro 15**

fixes some mobile issues

---

apps/semantic-cache/src/pkg/streaming.ts

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjcxOTRlYzVlMzlmZmQ2OWU2NTRjZGQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.e8DvFoeMDCwpebEIyVc5zp7r38L9XwD9dNEUj7xEZd0">Huly&reg;: <b>ENG-1765</b></a></sub>

feat: store stream in tinybird

---

apps/play/app/layout.tsx
apps/play/app/providers.tsx
apps/play/package.json
pnpm-lock.yaml

* Test A
* Test B
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjcxYmYxYjVlMzlmZmQ2OWU2NTRlZDMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.aT-9yRsfDY9Ylz_Qm_9tACuVDWSS0smSvskSh9LCWkw">Huly&reg;: <b>ENG-1766</b></a></sub>

chore: add Posthog to playground for tracking and survey usage

---

apps/dashboard/app/(app)/apis/[apiId]/select.tsx
apps/dashboard/app/(app)/semantic-cache/[gatewayId]/analytics/page.tsx
apps/dashboard/app/(app)/semantic-cache/[gatewayId]/logs/page.tsx
apps/dashboard/app/(app)/semantic-cache/[gatewayId]/logs/table.tsx
apps/dashboard/app/(app)/semantic-cache/form.tsx
apps/dashboard/app/(app)/semantic-cache/settings/delete-gateway.tsx
apps/dashboard/app/(app)/semantic-cache/settings/page.tsx
apps/semantic-cache/src/pkg/streaming.ts

This adds several fixes to improve responsiveness:
* Use horizontal overflow to avoid logs breaking onto two lines on mobile
* Minor fixes for /settings and /analytics pages
* Also corrects the redirect URL when creating new gateway
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjcxYzMwOTVlMzlmZmQ2OWU2NTRmMjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.sDcuE5_3pivE1epvL5xfiAL8d1saJl_x20tvfZd6jqU">Huly&reg;: <b>ENG-1767</b></a></sub>

feat: responsiveness for llmcache

---

apps/docs/mint.json
apps/docs/security/recovering-keys.mdx
pnpm-lock.yaml

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjcyOGU4NzVlMzlmZmQ2OWU2NTVlMTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.p6FxBRfrCjn6sEP2Ixic-l5WvafOCQstAZrd8PDTFt8">Huly&reg;: <b>ENG-1770</b></a></sub>

docs: explain vault and recovery

---

.changeset/small-fishes-glow.md

* Test A
* Test B
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njc0MTdhNDVlMzlmZmQ2OWU2NTgwYWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.uwJ2SoEPDcxst0aneIn2Hf_tB3X8KjvpdoPWgijdH20">Huly&reg;: <b>ENG-1779</b></a></sub>

chore: Hono changeset

---

apps/semantic-cache/package.json
apps/semantic-cache/src/pkg/streaming.ts
packages/cache/package.json

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjczZGE4NjVlMzlmZmQ2OWU2NTdhZmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.D6pFiZE9pr4uIINReZzWQQT9XqvtaGjU2Pxvo6oQcOk">Huly&reg;: <b>ENG-1776</b></a></sub>

fix: return an error when the openai call fails

---

apps/play/app/page.tsx

* remove layout shift on curl equivalent
* decrease opacity for frozen auto-filled fields
https://github.com/unkeyed/unkey/assets/10366880/62c2dd00-a052-4585-b6c0-317ea779d314
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njc5ODcyYjJhNmFiOWVlZjU1NzcxMjciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.9qiey97gVaLp4nBtRpyt3nG6nD6TtREkqdLTZxXuz_Y">Huly&reg;: <b>ENG-1788</b></a></sub>

chore(play): remove cls and decrease opacity for frozen fields

---

apps/play/app/page.tsx

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njc5OTRmYjJhNmFiOWVlZjU1NzcyZjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.R5uVKvXirHFfmeQDTecuj1VBs1Zfp9Hls2gaAvytkkI">Huly&reg;: <b>ENG-1790</b></a></sub>

chore(play): reinforce schema for expiration date, ownerId, prefix and more

---

apps/semantic-cache/src/pkg/util/index.ts

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdiZTI5NjJhNmFiOWVlZjU1N2FkMGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.6iHMgJNh5UOHgXatRPEFQdnB26srkvFGNwHQFp6cltM">Huly&reg;: <b>ENG-1798</b></a></sub>

feat: format quotes for llmcache

---

apps/dashboard/app/(app)/semantic-cache/[gatewayId]/logs/table.tsx
apps/dashboard/app/(app)/semantic-cache/[gatewayId]/settings/page.tsx

Handles long strings that can overflow the <Code /> element

fix: handle long responses / gateway names

---

apps/semantic-cache/src/pkg/streaming.ts

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdjMjIzYTJhNmFiOWVlZjU1N2I4M2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.nQHTFlxdz1JvRiqHvj_kdFh-gUgN6juIIyx2jDeXI6g">Huly&reg;: <b>ENG-1804</b></a></sub>

fix stream formatting

---

.changeset/nasty-countries-behave.md
packages/cache/src/swr.ts

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdjMjU2MTJhNmFiOWVlZjU1N2I5Y2YiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.6BnjtbSKR4TMwmFTgA3iQhGnA02N2mcPdduNO-F_wB4">Huly&reg;: <b>ENG-1805</b></a></sub>

fix(cache): make sure to await the revalidation promise before returning it

---

.changeset/funny-melons-know.md
packages/cache/README.md
packages/cache/src/swr.ts

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdjMmYwZTJhNmFiOWVlZjU1N2M1OGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.7v8IFGZNFMDXlnxC1MsrtAbQWzcjpNND2x-Kn_uYGyY">Huly&reg;: <b>ENG-1807</b></a></sub>

refactor(swr.ts): reformat code for better readability and consistency

---

apps/agent/pkg/connect/middleware_logging.go
apps/api/package.json
apps/api/src/routes/v1_keys_createKey.ts
apps/billing/package.json
apps/dashboard/package.json
apps/gateway/package.json
apps/semantic-cache/package.json
apps/webhooks/package.json
apps/workflows/package.json
apps/www/package.json
internal/db/package.json
internal/encryption/package.json
packages/cache/package.json
pnpm-lock.yaml
tools/local/package.json
tools/migrate/package.json

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdjNWZlYzJhNmFiOWVlZjU1N2M5OTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.evkH9_15pcLzzBnGlnAmWHEN_ePi6QOUmwjEDQiNGAc">Huly&reg;: <b>ENG-1809</b></a></sub>

fix: move as much out of the transaction as possible

---

apps/agent/schema.json

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdlNjg1ZDJhNmFiOWVlZjU1OTQyNzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.5eza1Nu6F_TI9WFt_YCSubF7H47PP8stum_iAW8ZYkw">Huly&reg;: <b>ENG-1815</b></a></sub>

feat(blog): add new cover images for blog posts

---

apps/agent/cmd/agent/agent.go
apps/agent/pkg/cache/middleware/tracing.go
apps/agent/pkg/connect/middleware_tracing.go
apps/agent/pkg/connect/ratelimit.go
apps/agent/pkg/connect/service.go
apps/agent/pkg/tracing/axiom.go
apps/agent/pkg/tracing/trace.go
apps/agent/services/eventrouter/service.go
apps/agent/services/ratelimit/middleware.go
apps/agent/services/ratelimit/pushpull.go
apps/agent/services/ratelimit/ratelimit.go
apps/agent/services/ratelimit/service.go

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdlNzAwZDJhNmFiOWVlZjU1OTQzMjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.5dMdDMh8hNjxZ5pNc-epDrBKGT8j0KgPouUFeg0jtes">Huly&reg;: <b>ENG-1816</b></a></sub>

feat: use a global tracer

---

apps/www/content/blog/building-authentic-comms.mdx
apps/www/content/blog/ocr-service.mdx
apps/www/content/blog/playground.mdx
apps/www/content/blog/semantic-caching.mdx
apps/www/content/blog/toolbox.mdx
apps/www/content/blog/using-unkey-with-auth.mdx

fix: updating tags 

---

apps/api/package.json
apps/api/src/pkg/db.ts
apps/api/src/routes/legacy_apis_listKeys.ts
apps/api/src/routes/v1_apis_deleteApi.ts
apps/api/src/routes/v1_apis_deleteKeys.ts
apps/api/src/routes/v1_apis_listKeys.ts
apps/api/src/routes/v1_keys_deleteKey.ts
apps/api/src/routes/v1_keys_updateKey.ts
apps/billing/package.json
apps/dashboard/lib/db.ts
apps/dashboard/package.json
apps/docs/audit-log/introduction.mdx
apps/gateway/package.json
apps/gateway/src/index.ts
apps/planetfall/tsconfig.json
apps/semantic-cache/package.json
apps/semantic-cache/src/pkg/db.ts
apps/webhooks/package.json
apps/workflows/lib/db.ts
apps/workflows/package.json
apps/www/lib/db.ts
apps/www/package.json
internal/db/src/index.ts
internal/encryption/package.json
pnpm-lock.yaml
tools/local/package.json
tools/migrate/package.json

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdmZjYxMTJhNmFiOWVlZjU1OTVhNjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.5zXOWk-2r-NKZ4nSTI8zHVRtEXn3E4S_EvCCIlEwSCw">Huly&reg;: <b>ENG-1823</b></a></sub>

fix: remove all direct drizzle-orm dependencies

---

apps/api/src/routes/v1_keys_createKey.ts
internal/metrics/src/index.ts

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjgwMTYxYjJhNmFiOWVlZjU1OTVjNDciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.97NEAA24cm9M9Kq5VJshXYnd9ZI2g-9blvPw5khSCFI">Huly&reg;: <b>ENG-1825</b></a></sub>

feat: add latency metrics for creating new keys

---

apps/engineering/mint.json
apps/engineering/services/agent/profiling.mdx

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjgyODg0ZDJhNmFiOWVlZjU1OTk4MzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.Mk9KLzn-vl4Hb8DGTz40Z-7hwDeBDi0D_4XeMj3NxMY">Huly&reg;: <b>ENG-1827</b></a></sub>

docs: add documentation for agent profiling endpoints and scripts

---

.changeset/silent-shrimps-rush.md
LICENSE
packages/api/LICENSE.md
packages/cache/LICENSE.md
packages/error/LICENSE.md
packages/hono/LICENSE.md
packages/nextjs/LICENSE.md
packages/ratelimit/LICENSE.md
packages/rbac/LICENSE.md

Adding individual MIT license and update license for entire monorepo
Fixes ENG-1197
* Test A
* Test B
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg0MTFhNDJhNmFiOWVlZjU1OWUzZTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.Hi6GPhwAdNyNtAlZa6HEncyNecs9CS3lIz8HJ5Yh9b8">Huly&reg;: <b>ENG-1837</b></a></sub>

chore: Adding license

---

.changeset/long-goats-look.md
packages/api/package.json
packages/cache/package.json
packages/error/package.json
packages/hono/package.json
packages/nextjs/package.json
packages/ratelimit/package.json
packages/rbac/package.json

* Test A
* Test B
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg0MzgwNzJhNmFiOWVlZjU1OWU5N2UiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.xq6AqWjOK4-ZP0upH_75l3OPSu42mLPZILLuslEb0k0">Huly&reg;: <b>ENG-1840</b></a></sub>

chore: Package update

---

apps/api/src/pkg/util/retry.ts
apps/api/src/routes/v1_keys_createKey.ts
apps/api/src/routes/v1_migrations_createKey.ts
apps/semantic-cache/package.json
packages/api/package.json
packages/cache/package.json
packages/hono/package.json
packages/nextjs/package.json
packages/ratelimit/package.json
packages/rbac/package.json

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg0NjVjMDJhNmFiOWVlZjU1OWVkOGQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.ptJoI4XCqLIAA1n6TfPmhcCtbZb6n0HTfXT_MZPUeMs">Huly&reg;: <b>ENG-1842</b></a></sub>

feat: implement retry mechanism for vault.encrypt calls

---

packages/error/package.json

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg0NzYzOTJhNmFiOWVlZjU1OWVmMGQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.S-t5wYMLccHlRzfEslT4HS0ytmIBBCJpxKPfmlCbW5U">Huly&reg;: <b>ENG-1843</b></a></sub>

chore(error): update package.json to include publishConfig and files field

---

apps/agent/pkg/connect/vault.go
apps/agent/services/vault/keyring/create_key.go
apps/agent/services/vault/keyring/decode_and_decrypt_key.go
apps/agent/services/vault/keyring/encrypt_and_encode_key.go
apps/agent/services/vault/keyring/get_key.go
apps/agent/services/vault/keyring/get_latest_key.go
apps/agent/services/vault/keyring/get_or_create_key.go
apps/agent/services/vault/keyring/roll_keys.go
apps/agent/services/vault/storage/s3.go
apps/api/src/pkg/ratelimit/agent.ts
apps/api/src/pkg/ratelimit/client.ts
apps/bounce/src/index.js
tools/artillery/leak.yaml

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg1YjQwYTJhNmFiOWVlZjU1YTExZWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.pIA7075rifZHIObABsjiPBvHWyp5o0UF64nf6Qrjf1Q">Huly&reg;: <b>ENG-1851</b></a></sub>

feat: add traces to vault

---

apps/www/components/blog/blog-code-block.tsx

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg3Njg2ZjJhNmFiOWVlZjU1YTI3NzgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.d_e4GFETLf67jyAn4x9QsLFjtGAEyOSJDD6Dsl865Cw">Huly&reg;: <b>ENG-1853</b></a></sub>

chore(blog): increase font size for code blocks from 12px to 13px

---

apps/agent/go.mod
apps/agent/go.sum
apps/agent/pkg/membership/redis_test.go
apps/agent/pkg/testutils/containers/redis.go
apps/agent/pkg/testutils/containers/s3.go
apps/agent/services/vault/integration/coldstart_test.go
apps/agent/services/vault/integration/migrate_deks_test.go
apps/agent/services/vault/integration/reencryption_test.go
apps/agent/services/vault/integration/reusing_deks_test.go
apps/agent/services/vault/storage/s3.go
pnpm-lock.yaml

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg3ZTI3ZDJhNmFiOWVlZjU1YTMxNzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.Ncexo-Db3_RbhEkBR9i-Xet7OvAafmnP0_S_E8Bi6Wc">Huly&reg;: <b>ENG-1854</b></a></sub>

test(vault): add integration tests for re-encryption and reusing DEKs

---

apps/agent/services/vault/keyring/get_key.go
apps/agent/services/vault/keyring/roll_keys.go
apps/agent/services/vault/roll_deks.go
apps/agent/services/vault/storage/interface.go
apps/agent/services/vault/storage/memory.go
apps/agent/services/vault/storage/middleware/tracing.go
apps/agent/services/vault/storage/s3.go

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg3ZWU2MzJhNmFiOWVlZjU1YTM0MjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.5KIxxSvifsAk_vc9gHxGxncSriVnd7cyQhgxBFyQ2qU">Huly&reg;: <b>ENG-1856</b></a></sub>

fix: return cache miss as boolean

---

.changeset/fast-wasps-care.md
apps/docs/libraries/ts/cache/overview.mdx
packages/cache/package.json
packages/cache/src/stores/index.ts
packages/cache/src/stores/upstash-redis.ts
pnpm-lock.yaml

adds a cache store for Upstash Redis. we use it in our codebase and I maybe others want to use it too. thanks for the cache package, helps us to delete a bit of biolerplate + have type safe caches!
* write a short script and try it?
I could also add an integration test using https://github.com/hiett/serverless-redis-http but I am not sure if that is required here.
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg2YTQwNjJhNmFiOWVlZjU1YTFlYzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.h48yDY3biMaeE4gIQqrQCEkkOD8h5QKl9zNzF38dvHs">Huly&reg;: <b>ENG-1852</b></a></sub>

feat: add upstash redis store

---

apps/api/src/pkg/analytics.ts
apps/api/src/pkg/errors/http.ts
apps/api/src/pkg/keys/service.ts
apps/api/src/routes/legacy_keys_verifyKey.ts
apps/api/src/routes/v1_keys_verifyKey.test.ts
apps/api/src/routes/v1_keys_verifyKey.ts
apps/docs/api-reference/keys/verify.mdx

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjhiYjQ2MThhZTA4ZTZhZWJiY2ViZWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.QwnydR2WGHqNODDgRtneJbw51CQ2v0MEdK066gy5zbA">Huly&reg;: <b>ENG-1865</b></a></sub>

feat: return all data for expired keys

---

apps/dashboard/app/(app)/semantic-cache/new/page.tsx
apps/dashboard/app/(app)/semantic-cache/new/util/generate-semantic-cache-default-name.ts
apps/dashboard/app/new/create-semantic-cache.tsx
apps/dashboard/app/new/page.tsx

- **feat(dashboard): add llm gateway to onboarding (missing backend call)**
- **chore(dashboard): implement llm gateway creation through onboarding**
https://github.com/unkeyed/unkey/assets/10366880/d00f5cd9-2891-43cc-ab1d-bd8b392564c1

feat(dashboard): add llm gateway to onboarding

---

apps/dashboard/app/(app)/semantic-cache/form.tsx
apps/dashboard/app/(app)/semantic-cache/new/page.tsx

Fixes #1900 
Manually go to /semantic-cache/new

fix: Semantic cache default name to client

---

apps/dashboard/next.config.js

fix: Add CSP headers to dashboard to prevent click jacking

---

.husky/pre-commit
package.json
pnpm-lock.yaml

Fixes #1896 
Basically they are the worst, and some people are not using them at Unkey. Let CI figure it out and part of our PRs require the steps taken to prevent blockers. 
- Test A
- Test B

chore: remove precommit hooks

---

apps/docs/mint.json

Removes posthost analytics from mintlify so we don't need to track things like, votes, searches, feedback, etc manually in our posthog dashboard.
Nothing to test.

chore: Remove our posthog in favor of Mintlify analytics 

---

apps/agent/Dockerfile
apps/api/src/routes/v1_keys_setPermissions.ts
apps/api/src/routes/v1_keys_setRoles.ts
apps/api/src/routes/v1_keys_updateKey.ts

- **docs: add examples to openapi specs**
- **chore(Dockerfile): change builder stage name to uppercase AS style(v1_keys_updateKey.ts): reformat code for better readability and consistency with openapi annotations**

permissions docs examples

---

apps/docs/mint.json
apps/docs/security/github-scanning.mdx

chore: Secret scanning docs

---

apps/www/app/layout.tsx
apps/www/lib/env.ts

Fixes #1940
It solves the previous requested features like resetting the

feat: Setting metadatabase with .env as well as zod

---

apps/www/app/pricing/discover.tsx

fix(landing/pricing): remove active key label

---

apps/api/src/routes/v1_ratelimit_limit.accuracy.test.ts
apps/docs/mint.json
apps/docs/quickstart/llm/index.mdx

chore: Adding Semantic Cache guide

---

apps/dashboard/app/(app)/authorization/permissions/[permissionId]/delete-permission.tsx

Fixes the delete modal. 
Fixes #1975 

fix: Delete modal long permissions

---

apps/dashboard/app/(app)/authorization/permissions/[permissionId]/delete-permission.tsx
apps/dashboard/components/multi-select.tsx

Fixes the Create Role modal even after selecting the long permission
Fixes #1974
- Test A
- Test B

fix: Create modal long permissions

---

apps/api/src/routes/v1_identities_updateIdentity.ts
apps/dashboard/app/(app)/layout.tsx

chore(dashboard/container): center and set maximum width

---

apps/dashboard/app/(app)/apis/[apiId]/loading.tsx

fix: remove sleep function from loader

---

apps/docs/libraries/ts/hono.mdx

fix: Update url

---

apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/delete-key.tsx

fix: Fix wording to say key instead of API in the delete key modal

---

apps/api/src/pkg/cache/index.ts

- **refactor(cache/index.ts): update keysByApiId cache initialization with custom fresh and stale values**
- **fix(cache): increase stale time for keysByApiId cache to 60 seconds**

chore: lower cache on list keys

---

apps/dashboard/app/(app)/authorization/roles/[roleId]/tree.tsx
packages/api/package.json
packages/hono/package.json
packages/nextjs/package.json
packages/ratelimit/package.json

This PR fixes the issue where the tooltip in the roles dashboard was being hidden behind the sidebar. It adjusts the positioning of the tooltip to ensure it's fully visible to users.
Fixes #2017
- Test A: Navigate to the roles dashboard and hover over a permission that triggers a tooltip.
- Test B: Verify that the tooltip appears above the hovered element and is fully visible.
- Test C: Test on various screen sizes to ensure the tooltip remains visible and doesn't get cut off or hidden behind other elements.

fix(#2017): Adjust tooltip positioning in roles dashboard

---

apps/api/src/pkg/analytics.ts
apps/api/src/routes/v1_keys_verifyKey.ts
apps/dashboard/lib/tinybird.ts
internal/tinybird/datasources/key_verifications.datasource
internal/tinybird/pipes/endpoint__get_latest_verifications.pipe

- **feat: log request body for verifications**
- **feat: request and response bodies**

log request body

---

apps/docs/libraries/ts/sdk/keys/verify.mdx

Added missing verify key response items. 
eng-1301
Check the docs page for the TS sdk verify key and make sure if reads ok and has required elements. 
- Test A
- Test B

fix: missing items in verify key response

---

tools/local/src/cmd/dashboard.ts

bug: Replacing vault secret with agent-auth-secret

---

apps/docs/api-reference/errors/code/UNAUTHORIZED.mdx
apps/docs/libraries/ts/ratelimit.mdx

This PR adds the missing documentation for the namespace parameter in the `RatelimitConfig` object in the `@unkey/ratelimit` SDK. The namespace parameter was previously missing from the documentation and was incorrectly described under the `rootKey` property. The addition of this information will provide users with clear guidance on how to properly configure the ratelimiting functionality using the SDK.
Fixes #2241 
- Verify that the namespace parameter is now correctly documented under the `RatelimitConfig` section in the `@unkey/ratelimit` SDK documentation.
- Ensure the information is clear and accurate, providing enough details for users to configure the namespace when using the SDK.
- Confirm that the rootKey property is now described correctly without confusion between the two …

docs: add missing documentation for namespace parameter in RatelimitConfig @unkey/ratelimit

---

oss.gg/3_follow_the_unkey_x_account.md

Added name to the followed list.
I followed Unkey dev on Twitter.
Fixes #2363 
- Test A
- Test B

docs: Update Followed unkey on X/twitter

---

apps/dashboard/app/(app)/logs-v2/components/control-cloud/index.tsx
apps/dashboard/app/(app)/logs-v2/components/controls/components/logs-datetime/components/datetime-popover.tsx
apps/dashboard/app/(app)/logs-v2/components/controls/components/logs-datetime/components/suggestions.tsx
apps/dashboard/app/(app)/logs-v2/components/controls/components/logs-datetime/index.tsx
apps/dashboard/app/(app)/logs-v2/components/controls/components/logs-datetime/utils/process-time.ts
apps/dashboard/app/(app)/logs-v2/components/controls/components/logs-filters/index.tsx
apps/dashboard/app/(app)/logs-v2/components/controls/index.tsx
apps/dashboard/app/(app)/logs-v2/page.tsx
apps/dashboard/lib/trpc/routers/logs/llm-search/utils.ts
apps/engineering/content/design/components/date-time.example.tsx
apps/engineering/content/design/icons.mdx
internal/icons/src/icons/clock.tsx
internal/icons/src/index.ts
internal/ui/src/components/date-time/components/actions.tsx
internal/ui/src/components/date-time/components/calendar.tsx
internal/ui/src/components/date-time/components/time-split.tsx
internal/ui/src/components/date-time/date-time.tsx

Adds datetime functionality to filters for logs v2
Validate it is in working order.

feat: datetime into logs v2

---

apps/dashboard/app/(app)/authorization/permissions/create-new-permission.tsx
internal/validation/src/index.ts

This adds a way to have nothing in the field, after entering the field and typing something in it.
- Test A
- Test B

fix: Permissions dialog errors on deleting text in option field

---

apps/www/app/careers/page.tsx

remove japan

---

apps/dashboard/app/(app)/apis/[apiId]/_overview/components/charts/index.tsx
apps/dashboard/app/(app)/logs/components/charts/hooks/use-fetch-timeseries.ts
apps/dashboard/app/(app)/logs/components/charts/index.tsx
apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/charts/bar-chart/hooks/use-fetch-timeseries.ts
apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/charts/index.tsx
apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/controls/components/logs-filters/index.tsx
apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/table/components/override-indicator.tsx
apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/table/components/ratelimit-overview-tooltip.tsx
apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/components/charts/hooks/use-fetch-timeseries.ts
apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/components/charts/index.tsx
apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/components/controls/components/logs-filters/index.tsx
apps/dashboard/components/ui/chart.tsx
apps/dashboard/lib/trpc/routers/utils/granularity.ts

fix: char selection and general issues

---

apps/dashboard/app/(app)/authorization/permissions/[permissionId]/settings-client.tsx
apps/dashboard/app/(app)/authorization/permissions/page.tsx
apps/dashboard/app/(app)/authorization/roles/[roleId]/settings-client.tsx
apps/dashboard/app/(app)/authorization/roles/page.tsx

fix: missing permissions and roles

---

apps/dashboard/app/(app)/apis/[apiId]/_overview/components/table/hooks/use-logs-query.ts
apps/dashboard/app/(app)/apis/[apiId]/_overview/components/table/logs-table.tsx
apps/dashboard/app/(app)/apis/[apiId]/_overview/components/table/query-logs.schema.ts
apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/table/hooks/use-logs-query.ts
apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/table/logs-table.tsx
apps/dashboard/app/(app)/ratelimits/[namespaceId]/_overview/components/table/query-logs.schema.ts
apps/dashboard/components/logs/hooks/use-sort.tsx
apps/dashboard/lib/trpc/routers/api/keys/query-overview-logs/utils.ts
internal/clickhouse/src/keys/keys.ts

feat: add sorting to api overview

---

internal/auth-migrator/package.json
pnpm-lock.yaml

fix: Downgrade node

---

internal/auth-migrator/package.json
packages/cache/package.json
pnpm-lock.yaml

fix: Pin versions of Node and typescript

---

apps/dashboard/app/auth/sso-callback/[[...sso-callback]]/route.ts

fix: oauth from request.url

---

apps/workflows/src/workflows/count_keys_per_keyspace.ts
apps/workflows/wrangler.toml

- **fix: skip test_ apis when calculating key counts**
- **fix: wrangler compat bs**

skip test apis

---

.github/workflows/job_test_api_local.yaml

ci: run PlanetScale container

---

.github/CODEOWNERS

chore: add Flo as code owner

---

apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/components/project-content-wrapper.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/deployments/components/controls/components/deployment-list-filters/components/environment-filter.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/deployments/components/rollback-dialog.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/deployments/components/table/components/actions/deployment-list-table-action.popover.constants.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/deployments/components/table/components/domain_list.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/deployments/components/table/components/skeletons.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/deployments/components/table/deployments-list.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/deployments/hooks/use-deployments.ts
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/deployments/page.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/details/active-deployment-card/index.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/details/project-details-expandables/index.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/details/project-details-expandables/sections.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/details/project-details-expandables/sections/open-api-diff.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/gateway-logs/context/gateway-logs-provider.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/gateway-logs/page.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/layout-provider.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/openapi-diff/components/deployment-select.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/openapi-diff/page.tsx
apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/page.tsx
apps/dashboard/components/logs/table-action.popover.tsx
go/demo_api/main.go

This PR;
- Renames context hook from `useProjectLayout` to `useProject`. Because its not just handling layout anymore
- Moves duplicated container into a shared component
- Fixes DeploymentList domain related layout shifts
- Just test the deployment flow and make sure nothing has regressed.

refactor: deploy improvements

---

.github/actions/setup-go/action.yaml
.github/actions/setup-node/action.yaml
.github/workflows/agent_build_publish.yaml
.github/workflows/apply-issue-labels-to-pr.yml
.github/workflows/autofix.ci.yaml
.github/workflows/build.yaml
.github/workflows/check_quotas.yml
.github/workflows/deploy.yaml
.github/workflows/deploy_trigger.yaml
.github/workflows/ghcr_retention_policy.yaml
.github/workflows/job_build_agent_image.yaml
.github/workflows/job_deploy_api_canary.yaml
.github/workflows/job_deploy_api_enterprise.yaml
.github/workflows/job_deploy_api_production.yaml
.github/workflows/job_deploy_api_staging.yaml
.github/workflows/job_deploy_logdrain_production.yaml
.github/workflows/job_deploy_workflows.yaml
.github/workflows/job_detect_changes.yaml
.github/workflows/job_test_api_canary.yaml
.github/workflows/job_test_api_local.yaml
.github/workflows/job_test_api_staging.yaml
.github/workflows/job_test_go_api_local.yaml
.github/workflows/job_test_unit.yaml
.github/workflows/release.yaml
.github/workflows/runbook-freshness-check.yaml
.github/workflows/semantic-pull-requests.yaml
internal/checkly/.github/workflow.yml

This upgrades some actions, but leaves most of them on their major version.
Let the actions run. 😄

fix: pin all GHA workflows to digests

---

apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/gateway-logs/constants.ts

This PR will add `fireworks.unkey.dev` to our `EXCLUDED_HOSTS` for gateway logs.
Path 1:
- Update your CH `api_requests_raw_v2` table and set one of the column `host` to `fireworks.unkey.dev`.
- Do it one more time but this time with a random host
- Make sure `fireworks.unkey.dev` doesn 't show up in gw logs.
Path 2:
- Make a request via fireworks
- Make sure you don't see it on your gw logs.

fix: excluded hosts for fireworks
