apps/docs/mint.json
apps/docs/sdk/get-started.mdx
apps/docs/sdk/keys/create.mdx
apps/docs/sdk/keys/revoke.mdx
apps/docs/sdk/keys/verify.mdx

Add documentation for the `@unkey/api` SDK, including a `get-started` page and pages for creating, revoking, and verifying keys.

feat(docs): add sdk documentation

---

packages/db/drizzle.config.ts
packages/db/package.json
pnpm-lock.yaml

Few reasons for this PR to be created
I've noticed that you are using version `0.19.1` of `drizzle-kit`, but you still have an outdated config file structure. In the [0.19.0](https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.19.0) release, we made some changes to the structure, and now you need to specify the driver you want to use when connecting to the database for the `push` or `introspect` commands.
I have updated the config file structure and upgraded `drizzle-kit` to the latest version, `0.19.2`. We recommend using this version instead of `0.19.0` or `0.19.1`. The reason for this recommendation is mentioned in the [0.19.2](https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.19.2) release.
I feel the need to report any potential issues that we are …

Upgrade drizzle-kit version and config

---

apps/docs/api-reference/apis/list-keys.mdx
apps/docs/api-reference/keys/create.mdx
apps/docs/api-reference/keys/verify.mdx

This PR updates a few things:
- `keyId` was missing from Create Key example response
- `createdAt` was an ISO format date string instead of unix epoch for List Keys example response
- typo/grammar fixes
- inconsistent use of tabs and spaces

Update api reference example responses

---

apps/docs/libraries/ex/functions/create_key.mdx
apps/docs/libraries/ex/functions/revoke_key.mdx
apps/docs/libraries/ex/functions/verify_key.mdx
apps/docs/libraries/ex/overview.mdx
apps/docs/mint.json

Closes #48 
This PR adds Elixir documentation to the Unkey site for the #48.

Add Elixir Documentation to the Unkey site

---

apps/docs/libraries/py/overview.mdx
apps/docs/libraries/py/services/apis.mdx
apps/docs/libraries/py/services/keys.mdx
apps/docs/mint.json

This PR adds documentation for the Python SDK.
Tried to keep it brief with an example for each method and other helpful links.
All methods and parameters are documented in depth in the API reference of the [unkey.py docs](https://jonxslays.github.io/unkey.py).

Add python sdk to docs

---

apps/web/app/(authenticated)/(app)/app/[apiId]/keys/[keyId]/page.tsx
apps/web/app/(authenticated)/(app)/app/[apiId]/keys/page.tsx
apps/web/app/(authenticated)/(app)/app/[apiId]/layout.tsx
apps/web/app/(authenticated)/(app)/app/keys/page.tsx
apps/web/app/(authenticated)/(app)/app/settings/page.tsx

This will stop caching of keys etc in our UI

This allows keys to be dynamic

---

packages/nuxt/playground/package.json

with this, we should be able to circulate this stackblitz for runnable nuxt+unkey starter:
https://stackblitz.com/github/chronark/unkey/tree/main/packages/nuxt/playground

chore: add missing playground dependency

---

apps/docs/api-reference/keys/update.mdx

- `remaining` had the parameter field of `expires`
- this is now updated to display `remaining`'s info

fix(docs): api reference for `remaining` now displays remaining usage

---

apps/web/app/(authenticated)/(app)/new/create-workspace.tsx
apps/web/middleware.ts

This PR self heals Unkey if some how an organization is orphaned (doesn't have a workspace). We will delete the organization out of Clerk and then have them recreate a pro workspace. 
This is a rare edge case, and should be better now we don't have slugs as well.

Self heal if organization is an orphan

---

apps/agent/pkg/cache/cache.go
apps/agent/pkg/cache/cache_test.go
apps/agent/pkg/cache/interface.go
apps/agent/pkg/cache/middleware/metrics.go
apps/agent/pkg/cache/middleware/tracing.go
apps/agent/pkg/cache/noop.go
apps/agent/pkg/cache/util.go
apps/agent/pkg/server/key_verify.go

repeated requests against non-existing resources will now be caught by the cache

feat(cache): store origin misses

---

apps/web/middleware.ts

When a user is logged in using our organization, we redirected them back to the payment page even if they were browsing a public page. This just  checks if the user is on a non public route and if they aren't then fire the checks. This also checks if the user has a workspace on non public pages, reducing load.

fix(middleware.ts): stops redirects on public pages

---

apps/web/app/(landing)/page.tsx

This fixes an issue where the image overflows and causes white space. 
#271

Homepage mobile fix

---

apps/web/pages/api/v1/stripe/webhooks.ts

This should now allow a the trial email to be sent if the user doesn't have a name or have a username but inserting there. An empty string "" seems to break the flow completely. So we replaced it with there
No issue but, related to alerting.

fix(stripe webhook): stripe webhook by using a non empty string

---

apps/web/app/(authenticated)/(app)/app/apis/[apiId]/create-key.tsx
apps/web/app/(authenticated)/(app)/app/keys/[keyId]/settings/actions.ts
apps/web/app/(authenticated)/(app)/app/keys/[keyId]/settings/page.tsx
apps/web/app/(authenticated)/(app)/app/keys/[keyId]/settings/update-key-name.tsx
apps/web/components/dashboard/api-key-table/index.tsx
apps/web/lib/trpc/routers/key.ts

- [X ] 🌟 New feature
This adds the ability to add a name to key creation, to key update and the key table. Allowing users to identify a key quickly.
Table: 
Key creation: 
Key Update:
Table: 
Creation: 
Updates:

KEY-132 feat: add name to key creations, key update and key table

---

apps/web/app/(landing)/templates/page.tsx
apps/web/lib/templates-form.ts
apps/web/lib/utils.ts

Implement URL filter parameters in the templates page, similar to Vercel Templates (for example), check "After this PR" to see the result in unkey.
N/A

chore: implement/sync url filter params for templates

---

internal/tinybird/endpoints/endpoint__billing_verifications_per_hour__v1.pipe

This commit adds a new endpoint for retrieving billing verifications per hour. The endpoint is implemented as a Tinybird pipe and uses SQL to query the `mv__verifications_per_workspace_per_hour__v1` materialized view. The query selects the `workspaceId`, `verifications`, and `time` columns from the view, filtering the results based on a provided `since` parameter.

feat(endpoint): add new endpoint for billing verifications per hour

---

apps/web/app/layout.tsx

When reviewing the code for Unkey, I noticed that my IDE (Webstorm) was throwing an error on `metadata` due to a key mismatch from `image` to `images`. This PR fixes this issue but imports the types and applies them using `satisfies` to ensure these errors won't be reintroduced.

chore: make layout metadata more typestrict

---

.husky/pre-commit
package.json
pnpm-lock.yaml

This PR adds Husky and Lint-Staged in order to execute Biome in a pre-commit hook. Husky manages commit hooks via Git, while lint-staged only runs Biome on the files you've modified in said PR to make the execution faster.

chore: add Husky and Lint-Staged

---

apps/web/components/dashboard/copy-button.tsx

Changed the icon that shows on click to verify copy has worked
KEY-248
Changed icon for copy button when clicked

KEY-248 fix(copybutton icon): changed the icon that shows on click to copy keys

---

.changeset/soft-spies-walk.md
packages/api/src/client.ts

Add typecasts to prevent `tsc` complaining about incorrect types.
```console
client.ts:126:9 - error TS2322: Type '{ result: Awaited<TResult> | undefined; }' is not assignable to type 'Result<TResult>'.
Type '{ result: Awaited<TResult> | undefined; }' is not assignable to type '{ result: TResult; error?: undefined; }'.
Types of property 'result' are incompatible.
Type 'Awaited<TResult> | undefined' is not assignable to type 'TResult'.
'TResult' could be instantiated with an arbitrary type which could be unrelated to 'Awaited<TResult> | undefined'.
126         return { result: await res.json() };
~~~~~~
client.ts:142:7 - error TS2322: Type '{ error: UnkeyError | undefined; }' is not assignable to type 'Result<TResult>'.
Property 'result' is missing in type '{ error: UnkeyError | undefined; …
```

fix: `@unkey/client` types

---

apps/web/app/(authenticated)/(app)/app/desktop-sidebar.tsx

Added hover tooltips to api navigation in sidebar
KEY-247
Added hover tooltip to API nav links in sidebar

KEY-247 feat(desktop-sidebar): added hover to sidebad api links

---

apps/web/components/landing/footer.tsx

Using client side navigation on the footer for the docs results in a 404. PR uses an `a` tag instead. 
404 page when clicking on the documentation link in the footer.
It should go the docs page.

fix: update footer navigation to 404 for Documentation link

---

apps/web/app/(authenticated)/(app)/app/settings/team/page.tsx

User with role "Member" shouldn't be able to change other user's role in Settings->Team page.
User with role "Member" could change other's role:
Fixed now:
https://github.com/unkeyed/unkey/issues/549

fix: member role shouldn't be able to change others role

---

apps/api/src/integration/remaining_is_consistent.test.ts
apps/api/src/pkg/testutil/request.ts
pnpm-lock.yaml

This commit adds a new integration test file `remaining_is_consistent.test.ts` that tests the consistency of the remaining count in the API. The test verifies that the remaining count consistently counts down as keys are verified.
The test performs the following steps:
1. Creates a new API using the `v1/apis.createApi` endpoint.
2. Creates a new key for the API using the `v1/keys.createKey` endpoint, with a specified remaining count.
3. Verifies the key by calling the `v1/keys.verifyKey` endpoint in a loop, decrementing the remaining count each time.
4. Checks that the key is valid and the remaining count is correct after each verification.
5. Checks that the key becomes invalid and the remaining count reaches 0 after all verifications.
6. Retrieves the key using the `v1/keys.getKey` …

feat(remaining_is_consistent.test.ts): add integration test for verifying remaining count

---

apps/web/components/dashboard/navbar.tsx

Added padding to navbar to stop buttong cutoff
key-296
Fix bug cutting off button in navbar in settings
check if fix looks right and causes no ui issues
- Test A
- Test B

fix: key-296 stopped general button from being cutoff

---

apps/web/components/dashboard/navbar.tsx

eng-344
removed margin causing issues with scrolling on some settings elements on navbar
Navbar looks and acts as intended

fix: removed margin on separator

---

.github/CONTRIBUTING.md
.github/actions/install/action.yaml
apps/docs/contributing/getting-started.mdx
examples/nextjs-expiration/next-env.d.ts
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Adds the `packageManager` field to package.json, which allows us to specify a package manager version with [Corepack](https://nodejs.org/api/corepack.html).
Fixes #793 
follow new install instructions

chore: use corepack to manage pnpm versions

---

apps/landing/components/analytics/analytics-bento.tsx

I was going through my first Unkey experience from 0 to deploy and at some point I could not properly copy the code snippet in the landing page when not clicking on the dedicated "copy" button.
This PR brings a UX improvement to the code editor through a temporary solution, which applies `user-select:none` (not ideal).
https://github.com/unkeyed/unkey/assets/10366880/b64ba0ee-51bc-444d-b537-aa6d0fc97279
---
Ideally, the line numbers should live in a different column inside of the code editor, all parallel to that line's code. That way we won't need to apply `user-select:none` anymore.
The code editor should eventually the ability to edit code, otherwise it may be better to rename it to code viewer.

chore(landing/editor): remove user-select for line numbers

---

apps/landing/components/hashed-keys.tsx

It didn't run on mikes, james or my phone before, probably cause we used hardcoded pixel values
this uses a -100% offset instead
also fixed padding and rounding

fix: one-way-hash animation on real mobile phones

---

apps/landing/components/analytics/analytics-bento.tsx

changed from leading-8 to leading-6 
before:
after:

fix: eng-950-landing-decrease-line-height-of-editor

---

apps/landing/components/rate-limits-bento.tsx

fix: make rate limits bento card more opaque

---

apps/dashboard/app/auth/layout.tsx

This pr calculates the exact screen size by removing the size of the navigation bar to avoid scrolling.
Fixes #1499

fix: scrolling error in login and registration area

---

apps/www/next.config.js
apps/www/package.json

This PR just adds an `pnpm analyze:build` command so that we can visualize bundles like this

perf(www): add next bundle analyzer

---

packages/hono/package.json
pnpm-lock.yaml

When working with hono our package fails on npm for legacy deps, if we use force it works properly. Updating to the latest and greatest.
* Test A
* Test B
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjczNTNlMDVlMzlmZmQ2OWU2NTc0ZWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.fvUPCCNNKGCvHeVl1ujeMkDppalOqMk2vT4wVQXLN6Q">Huly&reg;: <b>ENG-1775</b></a></sub>

chore: Adds latest hono to package to fix legacy dep errors

---

apps/dashboard/app/(app)/semantic-cache/[gatewayId]/settings/delete-gateway.tsx
apps/dashboard/app/(app)/semantic-cache/form.tsx

Adds Posthog events for creating and deleting gateways
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdiZTdhMjJhNmFiOWVlZjU1N2FkNzEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.Sx5wSQp60mtmDGww_QzL1fp9daMwEUrXaWge0dk6cMs">Huly&reg;: <b>ENG-1799</b></a></sub>

feat: add posthog to semantic-cache

---

apps/dashboard/app/(app)/desktop-sidebar.tsx

Unhide the semantic cache tab
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdjMWQ5ZjJhNmFiOWVlZjU1N2I3YmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.bviqQh33Agk4B8FkfzSwemY8pHSGeeyok24cXAWAE0w">Huly&reg;: <b>ENG-1803</b></a></sub>

chore: Show semantic cache in sidebar

---

apps/agent/pkg/membership/redis.go
apps/agent/pkg/ring/ring.go
apps/agent/services/ratelimit/ratelimit.go

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdkN2ExOTJhNmFiOWVlZjU1ODAwMWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.iGw3CUFdQNEH-6KR_SkIEjz_SLkF5fq1mpUW0ZKN4l0">Huly&reg;: <b>ENG-1811</b></a></sub>

fix(redis.go): handle nil values in members list fix(redis.go): log error when failing to cast value to string

---

apps/docs/libraries/ts/hono.mdx

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdmZjc5MDJhNmFiOWVlZjU1OTVhYzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.9PmoaQhCFc1AWgiIK2o1y24zk0QcBQgkpUcpERhjqUc">Huly&reg;: <b>ENG-1824</b></a></sub>

refactor(docs): remove explicit types in onError function parameters in hono.mdx

---

apps/agent/pkg/connect/service.go
apps/engineering/mint.json
apps/engineering/services/agent/profiling.mdx

* **feat(mint.json): add new page for Agent profiling under Services group feat(profiling.mdx): add documentation for agent profiling endpoints and scripts**
* **fix: use sha256 to prevent timing attacks**
<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjgyOGE5OTJhNmFiOWVlZjU1OTk4OTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.u6ItTzK0WTqGEUVz5UYM6kjfOpb9SI4KY1MtH20HPUM">Huly&reg;: <b>ENG-1828</b></a></sub>

fix: basic timing attack

---

apps/api/src/integration/sdk/verify_with_ratelimit.test.ts
apps/api/src/pkg/keys/service.ts
apps/api/src/pkg/ratelimit/client.ts

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjgzMTZiZTJhNmFiOWVlZjU1OWFiYTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.IgIToH_nU293fQctHgdzCLKkoOBZjwhi41vqEoFZNKI">Huly&reg;: <b>ENG-1835</b></a></sub>

fix: handle multiple ratelimit responses from agent correctly

---

apps/api/src/routes/v1_keys_updateKey.happy.test.ts
apps/api/src/routes/v1_keys_updateKey.ts

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njg5MGU5MjhhZTA4ZTZhZWJiY2M2NGQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.86OEPVq38WKj7E9Gq7N1wUJEeRyHa7b3-xzEO8Ze8Y0">Huly&reg;: <b>ENG-1863</b></a></sub>

fix: don't set ratelimitAsync to null when updating a key

---

internal/tinybird/pipes/endpoint__get_last_used.pipe

<sub><a href="https://huly.app/guest/unkey?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjhiYjkzZDhhZTA4ZTZhZWJiY2VkOTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamFtZXMtdW5rZXktNjY2YWYwNzktNjliNzJiMzYyNi05ZGM2MGUiLCJwcm9kdWN0SWQiOiIifQ.bAl--T4MtzTzPHtLr2sQve3bclZpSRT4yn2KTlwVBc8">Huly&reg;: <b>ENG-1867</b></a></sub>

fix: refactor SQL query to order by lastUsed descending and limit to 1 result

---

apps/api/src/pkg/keys/service.ts
apps/api/src/pkg/testutil/harness.ts
apps/api/src/routes/v1_keys_verifyKey.multilimit.test.ts

In order to share ratelimits across keys for a single identity, we need to use the identityId as ratelimit identifier instead of the keyId

fix: use the identityId as ratelimit identifier

---

apps/www/components/changelog/changelog-grid-item.tsx

Making the Changelog `code` the same as Blog is doing
Before
After

chore(landing/changelog): make the tagged text the same font-size as blog does

---

apps/www/app/hero/hero-main-section.tsx

For now, we don't have any badge/update to show in the Hero section, therefore hiding it temporarily.
Before
After

chore(landing): hide badge above hero

---

apps/dashboard/app/(app)/settings/root-keys/new/client.tsx

This PR makes sure the user is redirected to the root key listing page right after successfully creating a new root key.
The previous behavior was an issue because it only refreshed the `settings/root-keys/new` route which is the same creation form as the user just had submitted. In other words, the user would remain in the same root key creation form/submission  page, even after successfully submitting the form.
Before
https://github.com/user-attachments/assets/1a58b67d-9fb0-429c-b222-819994419671
After
https://github.com/user-attachments/assets/16ff2cbe-dfb7-479e-a654-4c137b51e932

fix(dashboard/root-keys): push to a different route instead of refreshing the same one, right after creating a root key

---

apps/dashboard/components/ui/button.tsx

The button only had `pointer-events-none` applied to the `disabled:` modifier
Added `opacity-50` to disabled modifier

chore(dashboard/button): add opacity-50 to disabled button

---

apps/dashboard/components/dashboard/root-key-table/index.tsx

On double click of the root key start, it redirects the user to the settings instead of having the user to click on 3 dots and then select the details to view the settings
https://www.loom.com/share/5432908be4ae44c9a93139e27ce7fe5f?sid=41ce8430-0c68-4dfe-b87b-6052d4afe2b0 
Fixes #1937
Go to the root key in settings and then double-click on the start of the root key that is shown
- [ x] If a UI change was made: Added a screen recording or screenshots to this PR

feat: double Click on Root Key start should redirect to settings

---

apps/agent/pkg/connect/ratelimit.go
apps/agent/pkg/connect/service.go
apps/agent/services/ratelimit/pushpull.go

I have a feeling this is preventing bufconnect to write the response sometimes, causing empty unary responses.
This could be the reason why our ratelimiting is flaky right now.

fix: raise the http timeouts

---

apps/semantic-cache/package.json
apps/semantic-cache/src/pkg/env.ts
pnpm-lock.yaml

This simply removes the no longer needed `@cloudflare/ai` package. That package is now deprecated:
https://developers.cloudflare.com/workers-ai/changelog/
No functional changes, just a bit of dependency cleanups.
- Run `dev` and `build` scripts in `apps/semantic-cache` and observe no issues
- Ensure `Ai` type still operates the same way

chore: remove @cloudflare/ai package

---

apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/page.tsx
packages/api/package.json
packages/hono/package.json
packages/nextjs/package.json
packages/ratelimit/package.json

This PR optimizes the Key Details UI for mobile devices by refactoring the Metric component to prevent text overflow and implementing a responsive grid layout in the parent component. These changes improve the readability and usability of the Key Details section on smaller screens.
Fixes #1989
- Test A: Open the Key Details page on various mobile devices (or use browser dev tools to simulate different screen sizes) and verify that all text in the Metric components is visible without overflow.
- Test B: Check the layout on different screen sizes to ensure it responds correctly:
- On mobile: should display 2 columns
- On small screens: should display 3 columns
- On medium and larger screens: should display 6 columns
https://github.com/user-attachments/assets/5753d5c4-524f-41bf-9a02-77833fb1d …

fix(#1989): Optimize Key Details UI for mobile

---

apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-enabled.tsx
apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-expiration.tsx
apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-name.tsx
apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-owner-id.tsx
apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-ratelimit.tsx
apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/settings/update-key-remaining.tsx

It's fixing the save button position on api/keys/settings page
Fixes #2048 
Just follow the issue steps.
all the cards are showing the button in the right position now.

fix: save button position on api/keys/settings page

---

apps/dashboard/app/(app)/settings/root-keys/new/client.tsx

It fixes the icon alignment when creating a root key. It also fixes some react warnings related to missing `key`.
Fixes #2054 
Just follow the steps to reproduce posted in the issue #2054

fix: Icon alignment when creating a root key

---

packages/ratelimit/README.md
packages/ratelimit/package.json

This PR adds README.md file for `@unkey/ratelimit` sdk
Fixes  (#2161)

docs: README.md for @unkey/ratelimit

---

oss.gg/7_create_a_template.md

In this pull request, I've integrated `Unkey` to provide route protection and rate limiting for the application for hackathon. This is a side quest to make a template using a framework.
- API Key Verification: Added middleware to verify API keys using `Unkey`. Only requests with valid API keys in the Authorization header (Bearer token) are allowed to access protected routes.
- Rate Limiting: Implemented rate limiting using the `Unkey` rate limits API. Each request is checked against the defined rate limit.
Fixes #2292 
```bash
git clone https://github.com/djnovin/unkey-rust-actix
```
```bash
cargo run
```
``` bash
curl …
```

docs: Protecting and Rate Limiting Rust Actix Web API Template

---

apps/dashboard/app/api/webhooks/stripe/route.ts

This adds Customer alert to the slack channel. 
So we know who has a free trial. 
It tells us the product, amount, name and email.

chore: Add free trial alert to our customers slack channel

---

apps/dashboard/app/auth/actions.ts
apps/dashboard/app/auth/hooks/useSignIn.ts
apps/dashboard/lib/auth/types.ts

Add a r/l to radar
Radar prep for future 
- Test A
- Test B

chore: Radar prep

---

.github/workflows/job_test_go_api_local.yaml

Simplifies the Go API testing workflow by removing the test sharding strategy and replacing the test command with `make test-full`. This change eliminates the matrix configuration that previously split tests into 8 shards, streamlining the CI process.
- Run the GitHub workflow to ensure tests execute properly with the new configuration
- Verify that `make test-full` runs all tests correctly in the Go directory

ci: run all go tests in one action to reduce installs due to ratelimits

---

.github/workflows/deploy.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/112](https://github.com/unkeyed/unkey/security/code-scanning/112)
The best way to fix this issue is to add an explicit `permissions` block to the root of the workflow file. This block will apply to all jobs unless overridden in individual jobs. Based on the provided code, most jobs likely only require `contents: read`, while those interacting with pull requests (if any) might need additional permissions. This fix adheres to the principle of least privilege.
Steps for implementation:
1. Add a `permissions` block at the root of the workflow file, specifying `contents: read` for general operations.
2. If specific jobs require additional access (e.g., `pull-requests: write`), override the permissions within those jobs. …

Potential fix for code scanning alert no. 112: Workflow does not contain permissions

---

.github/workflows/ghcr_retention_policy.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/78](https://github.com/unkeyed/unkey/security/code-scanning/78)
To address the issue, add a `permissions` key at the root of the workflow or within the specific job (`clean`) to explicitly limit the permissions of the `GITHUB_TOKEN`. Since the workflow appears to involve container management and uses a personal access token, the `contents: read` permission should be sufficient for reading repository contents, while no additional permissions should be granted unless specifically required.
Changes should be made to the `.github/workflows/ghcr_retention_policy.yaml` file:
- Insert a `permissions` block at the root level of the workflow or within the `clean` job to ensure least privilege is adhered to.
- The …

ci: Potential fix for code scanning alert no. 78: Workflow does not contain permissions

---

.github/workflows/job_test_agent_local.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/53](https://github.com/unkeyed/unkey/security/code-scanning/53)
To address the issue, the `permissions` key should be added to the workflow file. The permissions block should assign the least privileges necessary for the workflow's tasks. Since the workflow involves checking out code and possibly interacting with repository contents during the install step, the `contents: read` permission is sufficient. Write permissions are not required based on the provided steps.
The `permissions` block should be added at the top level of the workflow file to apply to all jobs in the workflow. This ensures consistency and avoids the need to define permissions for individual jobs.
---
_Suggested fixes powered by Copilot Autofix. …

ci: Potential fix for code scanning alert no. 53: Workflow does not contain permissions

---

.github/workflows/job_deploy_logdrain_production.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/52](https://github.com/unkeyed/unkey/security/code-scanning/52)
The best way to fix this issue is to add a `permissions` key at the job or workflow level to explicitly define the required permissions. Since the workflow involves tasks like checking out code, installing dependencies, building, and deploying, the minimal permissions needed include `contents: read` (to read repository contents) and potentially other specific permissions, such as `deployments: write` if required for deployment. 
The fix involves editing `.github/workflows/job_deploy_logdrain_production.yaml` to include a `permissions` block at the workflow or job level. This block will specify the least privileges required for the deployment process. …

ci: Potential fix for code scanning alert no. 52: Workflow does not contain permissions

---

.github/workflows/check_quotas.yml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/29](https://github.com/unkeyed/unkey/security/code-scanning/29)
To fix the issue, we need to add a `permissions` block to the workflow. This block should specify the least privileges required for the workflow to function correctly. Based on the workflow's operations, the `contents: read` permission is sufficient, as the workflow does not appear to require write access to the repository.
The `permissions` block can be added at the root level of the workflow to apply to all jobs, or specifically to the `quota-check` job. In this case, adding it at the root level is more concise and ensures consistency across all jobs.
---

ci: Potential fix for code scanning alert no. 29: Workflow does not contain permissions

---

.github/workflows/job_deploy_workflows.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/109](https://github.com/unkeyed/unkey/security/code-scanning/109)
To fix the issue, we will add a `permissions` block at the root of the workflow. This block will define the minimal permissions required for the workflow to function correctly. Based on the workflow's steps:
- The `contents: read` permission is needed for the `actions/checkout` step to read the repository's contents.
- No other permissions appear to be required for the `GITHUB_TOKEN`.
The `permissions` block will be added after the `name` field (line 1) to apply to all jobs in the workflow.
---

ci: Potential fix for code scanning alert no. 109: Workflow does not contain permissions

---

.github/workflows/job_clickhouse_migration_preview.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/40](https://github.com/unkeyed/unkey/security/code-scanning/40)
To address the issue, add a `permissions` block to the root of the workflow or directly to the `deploy` job. Since the workflow involves actions like code checkout (`actions/checkout`) and migration (`goose`), it likely requires `contents: read` for repository files and possibly no additional write permissions. Adding the `permissions` block with `contents: read` at the root of the workflow ensures that all jobs inherit the least privilege necessary, while specific jobs can override this if needed.
**Steps:**
1. Add a `permissions` block at the workflow root to set `contents: read` for all jobs by default.
2. If specific jobs need write permissions …

ci: Potential fix for code scanning alert no. 40: Workflow does not contain permissions

---

.github/workflows/job_deploy_api_production.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/46](https://github.com/unkeyed/unkey/security/code-scanning/46)
The fix involves adding a `permissions` key to the workflow file to explicitly define the minimum privileges required for the `GITHUB_TOKEN`. Based on the actions and steps used in the workflow, the following permissions are required:
- `contents: read`: Needed for the `actions/checkout@v4` step to access the repository's code.
- `deployments: write`: Needed for the `wrangler deploy` command to deploy the application.
The `permissions` key can be added at the root of the workflow (applies to all jobs) or specifically to the `deploy` job. Here, we will apply it to the `deploy` job as it ensures the least privilege principle is followed more granularly. …

ci: Potential fix for code scanning alert no. 46: Workflow does not contain permissions

---

.github/workflows/job_deploy_api_enterprise.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/49](https://github.com/unkeyed/unkey/security/code-scanning/49)
To fix the issue, we need to add a `permissions` block to the workflow. This block should explicitly define the least privileges required for the workflow to function correctly. Based on the workflow's operations, the `contents: read` permission is sufficient for the `GITHUB_TOKEN` used in the `install` step. No other permissions appear to be required.
The `permissions` block can be added at the root level of the workflow to apply to all jobs, or specifically to the `deploy` job. In this case, adding it at the root level is more concise and ensures consistency across all jobs.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before …

ci: Potential fix for code scanning alert no. 49: Workflow does not contain permissions

---

.github/workflows/job_test_api_canary.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/56](https://github.com/unkeyed/unkey/security/code-scanning/56)
To fix the issue, we will add a `permissions` block to the workflow. Since the workflow involves checking out code and running tests, it likely only requires `contents: read` permission. We will add this block at the root level of the workflow to apply it to all jobs. If any job requires additional permissions in the future, they can be specified individually.
---

ci: Potential fix for code scanning alert no. 56: Workflow does not contain permissions

---

.github/workflows/job_test_api_local.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/59](https://github.com/unkeyed/unkey/security/code-scanning/59)
To fix the issue, we need to add a `permissions` block to the workflow. This block should specify the minimal permissions required for the workflow to function correctly. Based on the provided code, the workflow primarily reads repository contents and uses the `GITHUB_TOKEN` for installation purposes. Therefore, the permissions can be limited to `contents: read`.
The `permissions` block should be added at the root level of the workflow to apply to all jobs, as there is no indication that different jobs require different permissions.

ci: Potential fix for code scanning alert no. 59: Workflow does not contain permissions

---

.github/workflows/job_test_unit.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/61](https://github.com/unkeyed/unkey/security/code-scanning/61)
To resolve the issue, we will add a `permissions` block to the workflow. This block will explicitly specify the minimum permissions required for the workflow to function correctly. Based on the workflow's usage of `actions/checkout` and `secrets.GITHUB_TOKEN`, the workflow needs access to the repository contents (`contents: read`). Since there is no evidence of other actions requiring elevated permissions (e.g., write access), the minimal permission `contents: read` will suffice.
The `permissions` block will be added at the workflow level (root level) to apply to all jobs in the workflow. This ensures uniform permission restrictions across all jobs. …

ci: Potential fix for code scanning alert no. 61: Workflow does not contain permissions

---

.github/workflows/test_agent_local.yaml

Potential fix for [https://github.com/unkeyed/unkey/security/code-scanning/68](https://github.com/unkeyed/unkey/security/code-scanning/68)
To resolve the issue, add a `permissions` block at the root level of the workflow or within the `test_agent_local` job. The block should specify the least privileges required for this workflow. Based on the actions and steps in the workflow, `contents: read` is sufficient for tasks like checking out the repository and building/testing the code. No write permissions appear necessary.

ci: Potential fix for code scanning alert no. 68: Workflow does not contain permissions

---

go/internal/services/keys/validation.go

Replace the deprecated `golang.org/x/exp/slices` import with the standard library `slices` package. This change updates the import to use the officially supported slices package that was moved from the experimental module to the standard library.
- Verify that all existing functionality using slices operations continues to work
- Run the test suite to ensure no regressions

fix: use stable slices package

---

go/apps/api/openapi/openapi-generated.yaml
go/apps/api/openapi/spec/paths/chproxy/metrics/index.yaml
go/apps/api/openapi/spec/paths/chproxy/ratelimits/index.yaml
go/apps/api/openapi/spec/paths/chproxy/verifications/index.yaml
go/apps/api/openapi/spec/paths/v2/liveness/index.yaml

Removes unnecessary quotes around boolean values in the `x-speakeasy-ignore` property across multiple OpenAPI specification files. This change standardizes the format of boolean values in the API specification by changing `"true"` to `true`.
- Verify that the OpenAPI spec still validates correctly
- Ensure that the Speakeasy SDK generation works as expected with the updated format

fix: speakeasy ignore directive is ignored if it's a string

---

tools/migrate/environment-migrate.ts

This PR adds a migration script to move environment data from the `environment` field to the `meta.environment` field for keys in a specific workspace. The script:
1. Connects to the MySQL database
2. Queries keys in batches of 1000 from workspace "ws_39g5eLLQTX8bVdbsGK9Dke" that have an environment value
3. For each key, checks if meta.environment already exists
4. If not, adds the environment value to the meta JSON object
5. Updates the key record with the new meta data
- Run the migration script against a test database to verify it correctly moves environment data to meta.environment
- Verify that keys in the specified workspace have their environment values properly migrated to meta.environment
- Check that no data is lost during the migration process

chore: utility script to move environments to meta

---

apps/dashboard/components/navigation/sidebar/user-button.tsx

A user couldn't find out what email account they're using. We would only show this if they had subscibed and looked at the team page.
This adds a small display in the dropdown menu of the user button component. The email is shown at the top of the dropdown with text ellipsis for overflow handling and a tooltip for viewing the full email when hovering.
- Open the user dropdown menu and verify the user's email appears at the top
- Test with various email lengths to ensure text ellipsis works correctly
- Hover over truncated emails to confirm the full email appears in the tooltip

feat: show user's email

---

go/pkg/db/schema.sql
go/pkg/partition/db/schema.sql
internal/db/src/schema/deployments.ts
internal/db/src/schema/util/longblob.ts

This adds the ability to use longblob versus text / blob so we can store openapi specs that are larger
This adds the ability to use longblob versus text / blob so we can store openapi specs that are larger
- Test A
- Test B

fix: Use long blob versus blob text

---

go/apps/api/integration/root_keys/root_keys_test.go
go/cmd/ctrl/main.go
go/internal/services/keys/get.go
go/internal/services/keys/status.go
go/pkg/testutil/seed/seed.go

Fixes #4082 
When using an API key for a disabled workspace we shall not panic anymore, + adds tests for all root key statuses
Create Root Key, in your local db set enabled to 0 for your workspace
Call any API you should get a nice error message saying the workspace is disabled.

fix: panic when caling api with root key for disabled workspace
